### ISSUE TITLE
Add settings to disable tapping on words

### ISSUE THREAD

**Issue by nonetrix** [birchill/10ten-ja-reader#1005]
On Kiwi browser or Firefox when I try to select a sentence to copy and paste it, the pop up dictionary will appear. It would be great if this could be disabled so it's easier to select text I only want the puck to work

**Comment by birtles** [comment]
Sounds like a reasonable request!

**Comment by nonetrix** [comment]
Thanks! When can this be expected in a release if it's not too much to ask? No rush, best to make sure everything is stable

**Comment by birtles** [comment]
You're welcome!

Recently reviews on addons.mozilla.org take a long time (I think this extension has been marked as a popular extension so now it needs to go through manual review) so I've been releasing less frequently. I want to add a few more features before triggering the next release so maybe a couple of weeks, plus one week for review. Is that too long?

**Comment by birtles** [comment]
@nonetrix Just to let you know, version 1.15 has now been released which includes this setting.
