### ISSUE TITLE
It's not possible to select individiual words on the popup

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#1007]
When selecting a range of text from the popup (click & drag with the mouse), the selected range is immediately obscured by this UI

![image](https://user-images.githubusercontent.com/28300/200173446-5a9f2fa3-0685-48ca-bb65-93241f78ea1b.png)

My expectation would be that after I select individual words, I can copy them e.g. for further research. The first part of the interaction, the highlighting using the mouse, works just as normal. Consequently I would expect to be able to interact with the highlighted part just as normal.

Perhaps the "Copy entire entry" feature could move to a button instead? Maybe in the area where the close button lives.

**Comment by Tomalak** [comment]
...maybe file this under "surprising UI"/"don't make me think".

It's just not how all the other "highlight, then do something" interactions work on a computer. Practically speaking, it bars the user from using both the keyboard shortcuts and the context menu, so I don't think it's an optimal compromise here.

**Comment by birtles** [comment]
Sorry for the delay in following up here.

Oh, that's interesting. I hadn't really thought about that use case. I think we could probably make this work by, for example, checking if there is a selection within the popup, and, if there is, not triggering the copy overlay.

Do you think that would make sense?
