### ISSUE TITLE
[Feature Request] Mouse Hover Support

### ISSUE THREAD

**Issue by trd-db** [birchill/10ten-ja-reader#1009]
I've been using this extension for a while on Safari for iOS,and it's great! However, some of the sites I use have Japanese text that appears only on mouse hover. As of now I can manage to get the hovered text to show up a moment, then when I move the puck, the hovered text goes away. Would it be possible to implement the ability to make the puck send a mouse hover to the web page wherever the puck is pointing? Thanks!

**Comment by birtles** [comment]
Hi @trd-db! Thank you very much for your feedback and for using 10ten on Safari for iOS! Sorry for my delay in getting back to you.

At the moment, the puck should already be sending a mouse hover to the web page ([source reference](https://github.com/birchill/10ten-ja-reader/blob/21f63e681dd24c8b8c6b881d9821bafec63853f7/src/content/puck.ts#L451-L457)) so I'm not sure why it's not working.

Can you tell me which Web page it's not working on?

**Comment by trd-db** [comment]
I'm specifically referring to mokuro, a program which generates html files for manga with OCR'd text. On hover, the text shows up, but the 10ten puck isn't making the text box show up. 

The repo has a example page hosted: https://github.com/kha-white/mokuro

**Comment by birtles** [comment]
Thank you! I see, I can reproduce that issue now.

It appears to be because that page uses CSS `:hover` styles to show the text elements. However, the synthetic (untrusted) events generated by the puck will not trigger `:hover` styles ([SO reference](https://stackoverflow.com/a/17226753)).

Perhaps we can add a specific handling for mokuro to peek into the hidden text elements.

**Comment by trd-db** [comment]
That would work, if there was a good way for it to detect it was on a mokuro page, as long as the look ups were made possible on mobile.

**Comment by birtles** [comment]
First attempt was somewhat successful, but only when the OCR'ed text happens to line up quite closely with the original text:

https://user-images.githubusercontent.com/1232595/204990353-36e484a5-c2a8-423f-bd2f-046a37decf89.mp4

I'm going to try again, this time making the text boxes actually show up.

**Comment by birtles** [comment]
Looking at bit better

https://user-images.githubusercontent.com/1232595/205013463-248a521d-088a-4630-9625-88c169b0e042.mp4

**Comment by birtles** [comment]
On iPhone

https://user-images.githubusercontent.com/1232595/205014126-28f8d0d7-f36d-40f7-a97f-017f883fe6f1.MP4
