### ISSUE TITLE
Add option to turn off alt/title attribute interpretation

### ISSUE THREAD

**Issue by birtles** [birchill/10ten-ja-reader#104]
As reported [here](https://addons.mozilla.org/en-US/firefox/addon/rikaichamp/reviews/1379344/):

> My only wish is for a toggle in the preferences that would let me turn image ALT/TITLE attribute interpretation off.

**Comment by ecchichuu** [comment]
I hope this can be implemented. Translation pop ups are getting in the way when looking at artwork on pixiv.

**Comment by birtles** [comment]
Thanks for bringing this up! (Comments like this really help to prioritize the work)

I like the idea of having it hidden by default and only show when you press <kbd>Shift</kbd> or something like that. (I currently never see it because I use the "hold to show" keys setting.)

**Comment by birtles** [comment]
I started working on this. I'm thinking of combining it with the existing "hold to show" keys setting.

I wonder if the following UI makes sense?

![image](https://user-images.githubusercontent.com/1232595/131935212-326a6172-b790-4811-9714-fea9fb4c671d.png)

**Comment by birtles** [comment]
Phew! That was a lot of work. Hopefully this does the trick though. I'll release it sometime next week.
