### ISSUE TITLE
No way to enable the extension in fullscreen webapps on iOS

### ISSUE THREAD

**Issue by fsestini** [birchill/10ten-ja-reader#1075]
I've tested the extension on real iPad with iOS 16, and emulated iPhone 14 Pro. In both cases there is no context menu (ctrl + click) entry for the extension, regardless of whether the option has been enabled in the settings. Not sure if the context menu functionality is broken, or if there's another way to show the menu that I'm not aware of.
The keyboard shortcuts like "alt + R" do not work on iPad with a connected external keyboard. This means the only way to enable the extension on a page is from the Safari toolbar, however this renders the extension unusable on fullscreen webapps that do not display the Safari toolbar.

**Comment by birtles** [comment]
Oh, that's an interesting problem. I'm not sure how Safari fullscreen webapps work. Do extensions run in them normally? Can you switch between fullscreen and not fullscreen mode?

> The keyboard shortcuts like "alt + R" do not work on iPad with a connected external keyboard.

On Safari we use a different shortcut key, Control + Command + R. Does that work?

**Comment by fsestini** [comment]
> Do extensions run in them normally?

You might have a point here. Control + Command + R does work in normal Safari, but it doesn't in "webapp" mode. Some other context menu entries from other extensions are also not shown in that mode.

> Can you switch between fullscreen and not fullscreen mode?

You can't, which makes me think this webapp thing looks more like a glorified WebView, rather than Safari on fullscreen.
Fullscreen webapps should have access to most browser javascript APIs like IndexedDB and service workers, so if there were a version of the extension distributed as a normal js library that could be embedded in the webapp on need, that *might* work. But that's a whole other project that goes beyond the scope of this issue 😄 
I'm not too familiar with the inner workings of iOS, but it seems difficult to make it work as it is. Unless you have other ideas, I'm good with closing this.

**Comment by birtles** [comment]
Sorry for the delay! Just to clarify, what is a fullscreen web app? It seems like when I add some web pages (e.g. jisho.org) to the homescreen they open Safari regularly but others behave more like an app (no browser toolbar and no extensions). I guess the difference is whether or not the Web page has a [Web app manifest](https://developer.mozilla.org/docs/Web/Manifest) or not? Does that sound right?

**Comment by birtles** [comment]
Thanks! That makes sense. In that case I don't know if there's much we can do here for now so I hope you don't mind if I close the issue for now.
