### ISSUE TITLE
Kanji dictionary not showing

### ISSUE THREAD

**Issue by vaer-k** [birchill/10ten-ja-reader#1080]
Today I find that the extension is only showing vocabulary definitions. I can no longer use tab to switch to kanji definitions. I'm on Firefox 111.0b1 with tenten 1.13.5. 
![image](https://user-images.githubusercontent.com/4069456/219120692-15861f61-e526-4c53-8f88-83017f1f857d.png)

**Comment by birtles** [comment]
Hi! Sorry to hear the kanji dictionary is not working. That normally means that the downloaded dictionary data is not available and 10ten is using the data bundled with the add-on which only includes a snapshot of the word dictionary.

If the kanji tab used to work that suggests that either Firefox deleted the extension data (perhaps the disk got too full?) or had trouble accessing it (perhaps the disk permissions changed?) or there is some bug in 10ten where it decided the downloaded dictionary data is no longer available.

I wonder if you can try forcing the data to download using the following steps:

1. Right-clicking the extension icon and choose "Manage extension"
2. Go to the "Options" tab
3. Go to the very bottom and click the "Check for updates" button

![image](https://user-images.githubusercontent.com/1232595/219249262-743cede0-8153-43bb-af2f-685b5c0476d5.png)

If there is some error, hopefully it will be displayed there.

**Comment by vaer-k** [comment]
Thank you for your advice. I appreciate your troubleshooting suggestions. The kanji tab did indeed used to work; it stopped working overnight. My disk has hundreds of gigabytes available, and as far as I can tell, 10Ten has all required permissions (see image below.) 

![image](https://user-images.githubusercontent.com/4069456/219441362-0eb09baf-da56-4b08-9cd5-f20b23c4a6d4.png)

Although, in the options of the extension management section, I don't see the same dictionary as you have displayed in your screen shot. See mine below.

![image](https://user-images.githubusercontent.com/4069456/219441293-636f3813-e435-4e18-96ac-ea97c674e6e2.png)

**Comment by vaer-k** [comment]
I uninstalled the extension, restarted firefox, and reinstalled the extension, but that didn't solve the issue.

**Comment by birtles** [comment]
Thanks for your patience and help in troubleshooting this. It's very odd. I'm not sure what could be happening.

If you enter `about:debugging` in the address bar, go to "This Firefox", then choose "Inspect" next to 10ten Japanese Reader, I wonder if you see any errors in the console there? Alternatively, maybe the Storage tab there, specifically the Indexed DB part, can tell us if the data is being stored or not.

I don't suppose you installed any other extensions recently? (Or perhaps they updated automatically? I've seen a few errors being reported that appear to be other extensions misbehaving.)

**Comment by vaer-k** [comment]
Of course, I'm happy to get any help at all. I don't see anything in Indexed DB, but there is something in Extension Storage:

![Screenshot_20230217_093222](https://user-images.githubusercontent.com/4069456/219726379-928beec1-102d-4530-bd15-0be3891ec0dd.png)
![Screenshot_20230217_093211](https://user-images.githubusercontent.com/4069456/219726406-7288161a-4bb0-4fc4-8298-ba19d20f3e27.png)

I haven't installed any new extensions recently, but it is possible that one my other extensions updated. I use a dozen or so. Are there any particular kinds of egregious troublemakers?

**Comment by birtles** [comment]
It looks like it's not saving the data at all. I don't suppose you've enabled "Always-on private browsing" or "Never remember history" mode by chance? Firefox does not yet support using IndexedDB in private browsing mode and there are also settings in Firefox that causes this to apply to extensions too.

There are some details in #148.

In term of conflicting addons, I've seen a few error reports coming from a Kagi extension recently.

**Comment by vaer-k** [comment]
> I don't suppose you've enabled "Always-on private browsing" or "Never remember history" mode by chance? 

Nope, don't use those. 

> In term of conflicting addons, I've seen a few error reports coming from a Kagi extension recently.

I don't use that one, and I can't identify any extensions I have installed that could present the same issue. 10ten is the only language-related extension I use. I tried disabling ublock, but that didn't seem to have any effect.

I wonder if it could be a Firefox update that is causing the issue.

**Comment by birtles** [comment]
Hmm, that's really odd. I'm using 111 at work and 112 at home without problems. Both systems are Windows 11.

I see that @CowFroggers is on Win 8.1 Enterprise. @vaer-k what OS are you on?

@CowFroggers thanks for checking all those builds. Just to confirm, did you try v111 with a new profile?

**Comment by birtles** [comment]
Wow, that's really helpful. I tracked down the changes between beta 1 and beta 3 but I don't see anything obvious there:

https://hg.mozilla.org/releases/mozilla-beta/pushloghtml?fromchange=FIREFOX_111_0b1_RELEASE&tochange=FIREFOX_111_0b3_RELEASE

Also, @vaer-k originally reported seeing the problem on 111.0b1.

I'll poke some people on the Firefox addons team but first I'd like to check if @vaer-k is on Windows 8 and/or using Developer Edition so we can narrow down the parameters.

**Comment by birtles** [comment]
Actually, never mind. I managed to reproduce this on my home computer so I can try to debug it there tomorrow. Thanks for reporting it!

**Comment by birtles** [comment]
It looks like this is coming from [bug 1247687](https://bugzilla.mozilla.org/show_bug.cgi?id=1247687) which adds support to worker modules in v111. We're loading the background script as a module (not sure why) and that appears to be broken.

It's an easy fix for Firefox (just drop the `{ type: 'module' }` part) but I need to check it doesn't break other browsers.

**Comment by birtles** [comment]
I still haven't quite worked out exactly what is going on, but I think Firefox 111 introduced support for worker modules but then put it behind a flag for non-Nightly versions ([source](https://searchfox.org/mozilla-central/rev/3067ba33c2202459aae52b7a0f7218a71fe5f7c3/modules/libpref/init/StaticPrefList.yaml#3931)).

So on Nightly (currently 112) they will work since the flag is enabled there. In release, that feature hasn't arrived so the `{ type: 'module' }` annotation will be ignored, but in 111 the `type` is parsed, but because the pref is disabled, it will throw (see https://hg.mozilla.org/mozilla-central/rev/1f5f65f28752).

[Hikibiki](https://hikibiki.app) appears to be unaffected, despite using workers with `{ type: 'module' }` because I believe the webpack setup is different there, causing the `{ type: 'module' }` annotation to be transpiled to `{ type: void 0 }`.

Which is all to say, I need to fix the extension but in the short-term, you might be able to get it to work by going to `about:config` and toggling `dom.workers.modules.enabled` to true (and possibly restarting the browser after that or perhaps simply disabling and re-enabling 10ten).

**Comment by vaer-k** [comment]
Thank you @birtles. You communication here is so appreciated. At this point I know you no longer need to know, but for the record I'm Firefox dev and Windows 11.

**Comment by birtles** [comment]
Not at all! Thank you @vaer-k and @CowFroggers! Thanks to your help, we identified this issue while it still only affects Firefox beta so that we can fix it before it affects Firefox release too (on March 14).

**Comment by VarNepvius** [comment]
> […] you might be able to get it to work by going to about:config and toggling dom.workers.modules.enabled to true (and possibly restarting the browser after that or perhaps simply disabling and re-enabling 10ten).

I can confirm that enabling the about:config-setting and then disabling and re-enabling 10ten in about:addons makes the Kanji tabs work again.

I am on 111.0b2 Dev Edition by the way

**Comment by birtles** [comment]
Thank you!

**Comment by birtles** [comment]
I've published 1.13.6 which should fix this. If anyone can confirm that would be great.

**Comment by VarNepvius** [comment]
> I've published 1.13.6 which should fix this. If anyone can confirm that would be great.

It does for me.

I double checked, that the above `about:config` setting is off (default) and briefly switched to 1.13.5 to confirm, that the upgrade really makes a difference.

Thanks @birtles !

**Comment by birtles** [comment]
Thank you @VarNepvius!

**Comment by vaer-k** [comment]
@birtles Works for me. What great and fast work! Thank you

**Comment by birtles** [comment]
Thanks @vaer-k!
