### ISSUE TITLE
semver-parser now supports typescript

### ISSUE THREAD

**Issue by asamuzaK** [birchill/10ten-ja-reader#1084]
FYI, [semver-parser](https://www.npmjs.com/package/semver-parser "semver-parser - npm") includes `*.d.ts` files since `v4.1.x`.
[sync-manifest-version.mjs](https://github.com/birchill/10ten-ja-reader/blob/main/utils/sync-manifest-version.mjs) can be rewritten to typescript.

Cheers.

**Comment by birtles** [comment]
Thanks!

I tried doing this and I feel like I tried every combination of `ts-node` flags and file extensions but I couldn't get it to work, mostly getting `ERR_REQUIRE_ESM` errors.

**Comment by asamuzaK** [comment]
Below worked.

1. Rename `utils/sync-manifest-version.mjs` to `utils/sync-manifest-version.mts`
2. Fix tsconfig.json:
   ```
     "compilerOptions": {
       ...
       "module": "esnext",
       "moduleResolution": "node16",
       ...
     }
   ```
3. Add test script in package.json:
   ```
     "scripts": {
       ...
       "sync-version": "node --loader ts-node/esm utils/sync-manifest-version.mts",
       ...
     },
   ```
4. Run `npm run sync-version`

**Comment by asamuzaK** [comment]
BTW, for Node 18 and above, it might be better to

```javascript
import { version } from '../package.json' assert { type: 'json' }
```

Then, you don't need `semver-parser` anymore.

**Comment by birtles** [comment]
Thank you! I gave that a go but it looks like it breaks all the other `.ts` files. I converted a bunch of the scripts over to `.mts`, added definitions for `__dirname`, and fixed the args used to call them but all the extension pages are now broken. It looks like this might be quite a bit of work after all.

**Comment by asamuzaK** [comment]
I can't send a PR due to an error in fork, so I'll write a PR as a comment here.

* Create a copy of `utils/sync-manifest-version.mjs` and rename it to `utils/sync-manifest-version.mts`.
* Create `tsconfig-mts.json` which extends `tsconfig.json` and save it in root.
  ```json
  {
    "extends": "./tsconfig.json",
    "compilerOptions": {
      "module": "esnext",
      "moduleResolution": "node16"
    },
    "include": [
      "utils/sync-manifest-version.mts"
    ]
  }
  ```
* Add `exclude` field in `tsconfig.json`.
  ```
  "exclude": ["./utils/sync-manifest-version.mts"],
  ```
* Add script in `package.json`.
  ```
  "sync-version": "ts-node --esm -P tsconfig-mts.json utils/sync-manifest-version.mts",
  ```

If it works as expected, remove `utils/sync-manifest-version.mjs` and update `version` script in `package.json`

**Comment by birtles** [comment]
Thank you so much!
