### ISSUE TITLE
Not working for Bing Chat

### ISSUE THREAD

**Issue by nicolasmaia** [birchill/10ten-ja-reader#1130]
10ten doesn't work on https://www.bing.com/search?q=Bing+AI

You might need either Edge or a useragent spoofer to be able to use Bing Chat, though

**Comment by birtles** [comment]
Thanks for reporting this. I can reproduce it. I'll look into it next week.

**Comment by birtles** [comment]
Seems to work fine in Firefox with a useragent spoof, but not in Edge.

Looks like it's related to Chromium not digging into shadow DOM for `caretRangeFromPoint` (and not supporting `caretPositionFromPoint` at all). Test case: https://8t4urf.codesandbox.io/

**Comment by birtles** [comment]
Seems like Safari has the same problem. Even `document.elementsFromPoint` doesn't dig into shadow trees. Instead we'll need to recursively do `element(s)FromPoint` on each shadow root until we get to some text. This could be quite a bit of work.
