### ISSUE TITLE
10ten makes buttons not work on some websites

### ISSUE THREAD

**Issue by ghost** [birchill/10ten-ja-reader#1144]
Using this extension on Chrome breaks random buttons in websites. I notice this a lot using Misskey and Pleroma frontend. The buttons just become unclickable when you are hovering them (they stop doing their hover animation, cursor doesn't turn to hand, clicking does nothing). Turning off 10ten fixes it.

It doesn't break the same buttons every time. But it happens often on random buttons. On Misskey it happens most of the time that entries in the context menus cannot be clicked. On PleromaFE it seems the "open in remote instance" button on the top right corner of a remote user's profile is prone to breaking while being hovered. It happens on other pages too sometimes but I can't remember specific examples.

Tested on Brave version 1.49.120, can't replicate in Firefox. Using Windows

**Comment by birtles** [comment]
Hi @dk3904!

Thank you for filing this issue. I'm sorry about the annoyance with those buttons.

I've spent the last two weeks completely rewriting how 10ten looks up text in Web pages and will (hopefully) submit the updated version to the Chrome Web store later today. That 🤞might🤞 fix it. If not, I will try to sign up for Misskey/PleromaFE to see if I can reproduce the issue. If you notice it on any other pages (that I don't need to sign up for) please let me know! Thank you!

**Comment by birtles** [comment]
Thanks for checking @dk3904! That's great news!
