### ISSUE TITLE
Popup style #1 not changing based on dark mode settings

### ISSUE THREAD

**Issue by nicolasmaia** [birchill/10ten-ja-reader#1161]
Popup style #1 seems to visually suggest that it automatically changes to dark mode when the system is also in dark mode. 

This isn't working for me on Firefox 112.0.1, as I only get the light mode theme regardless of dark mode settings. 

For reference, I have Zorin OS automatically change the system theme to dark mode at 6 PM. Firefox is set to automatically follow the system setting. I'm also using an add-on called Dark Reader that turns itself on when Firefox switches to dark mode. The add-on forces dark mode on sites that don't natively support it.

**Comment by nicolasmaia** [comment]
Odd, when I disabled the extension, it worked. When I reenabled it, it still worked.

Definitely a compatibility issue between the two extensions.

**Comment by birtles** [comment]
Closing this for now. Please let me know if you find a way to reproduce this.
