### ISSUE TITLE
Read radicals as corresponding kanji

### ISSUE THREAD

**Issue by birtles** [birchill/10ten-ja-reader#1205]
As reported on twitter: https://twitter.com/Koyama_Yamako/status/1668559058809282561

Specifically in this text:

「穎才新誌」の作⽂が抽象的⾔説に..

The ⽂ is using the radical U+2F42 instead of the kanji codepoint U+6587. Similarly for ⾔.

This is just a bug in the markup but we _could_ map radicals to kanji codepoints where there is a clear corresponding counterpart. (For bonus points, we could preserve the original codepoint and show it in the kanji tab for easier debugging, or even show the radical information since we already store that in the database.)

**Comment by Tomalak** [comment]
Not sure how often that happens in real-life text, but I think it makes sense to support this.

**Comment by birtles** [comment]
Fixed in bc23d70499d49120a8bc5a1481de6e5b23a9ae07

**Comment by birtles** [comment]
Version 1.15 has now been released which includes this fix.

**Comment by SaltfishAmi** [comment]
Sorry to dig this up, in current version radicals are recognized as kanjis when they are matched in the words dictionary, but in the Kanji tab only the proper kanjis are shown (kanjis that misencoded as radicals do not appear there).

![image](https://github.com/birchill/10ten-ja-reader/assets/14184974/f9b4ac0a-9860-4731-9153-f8017098a284)


Is this intended behavior? I could see this cause some potential confusion.

**Comment by birtles** [comment]
It's not intentional, I just never really thought much about the kanji tab behaviour. It's probably worth looking into if we can fix it.
