### ISSUE TITLE
Feature request: Add an option to show all kanji definitions for the entry

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [birchill/10ten-ja-reader#1238]
It would be helpful to have an option to show all (not just the first one) kanji definitions for the entry in the kanji tab. Usually an entry is no more than 4-kanji long, so having 4 kanji definitions should not be a problem.

**Comment by birtles** [comment]
I think this will be covered by #1138 which I hope to do soon.

**Comment by Konstantin-Glukhov** [comment]
I think this feature is way easier to implement than #1138. Plus it will cover #1138.

**Comment by birtles** [comment]
Fixed by ec7d6db23d51cca11fdd555be9dde0f937e72242.
