### ISSUE TITLE
Pop-up misplacement in webpages with frameset elements

### ISSUE THREAD

**Issue by SaltfishAmi** [birchill/10ten-ja-reader#1241]
# Example

https://web.archive.org/web/20190514165339/http://kokkai.ndl.go.jp/SENTAKU/syugiin/112/0110/11204130110006a.html

## Small problem

![image](https://github.com/birchill/10ten-ja-reader/assets/14184974/f0b0fde3-656d-4d6c-95f0-5e8d45b0fe25)

## Bigger problem

in the other direction - the highlighted text is in the brownish shade, which is completely obscured by the popup:

![image](https://github.com/birchill/10ten-ja-reader/assets/14184974/424de78f-24ad-42cc-a601-e31b181a770f)

# Cause

This page contains an IFrame which contains a Frameset containing two Frames... By removing some of the structural labyrinth, the misplacement disappeared:

![image](https://github.com/birchill/10ten-ja-reader/assets/14184974/23376053-f745-46f2-bd78-39078b840213)

I deleted one Frame from the Frameset (without any other modification to the DOM or stylesheets), and the main text body moved to the header area, but the pop-up and highlight are now in correct relative position.

**Comment by birtles** [comment]
Thanks for the report. I'll look into it. We have to jump through a lot of hoops to translate positions between iframes so I'm not surprised there are cases that are wrong.

**Comment by birtles** [comment]
Version 1.15 has now been released which includes this fix.
