### ISSUE TITLE
Text is no longer highlighted

### ISSUE THREAD

**Issue by Brawl345** [birchill/10ten-ja-reader#1297]
Thanks for 10ten reader, been using it for three years now!

Since the last update (I think?) the "text highlighting style" setting no longer works. The popup is still shown but the text is no longer highlighted. Using **Chrome 116** on **macOS**, but it also doesn't work in Chrome Canary.

Example:
<img width="662" alt="image" src="https://github.com/birchill/10ten-ja-reader/assets/5049892/71e1a856-44ed-4557-9a49-6dfde4f96d25">

Here "台風" should be highlighted, but it isn't. I also have these settings, don't know if they are relevant:

<img width="438" alt="image" src="https://github.com/birchill/10ten-ja-reader/assets/5049892/3f3e10b9-4823-4a16-bee5-9f79225399dd">

<img width="603" alt="image" src="https://github.com/birchill/10ten-ja-reader/assets/5049892/192c129a-a3e5-4386-a157-0d0a8d67f6cf">

**Comment by birtles** [comment]
Hi! Thanks for reporting this. That sounds very bad.

I made a small change to highlighting just before releasing the latest version to fix highlight styles on pages with strict CSP settings but I guess I didn't test Chrome properly.

I'm away from my computer now but can I ask:

1. Does this happen on all websites?
2. Are there any error messages in the JavaScript console, e.g. CSP errors?

Thank you and sorry for the inconvenience!

**Comment by Brawl345** [comment]
No problem! After highlighting it shows this in the console:

```
Denying load of chrome-extension://pnmaklegiibbioifkmfkgpfnmdehdfan/css/selection.css. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

GET chrome-extension://invalid/ net::ERR_FAILED
ensureHighlightStyles @ 10ten-ja-content.js:10104
highlightRegularNode @ 10ten-ja-content.js:10075
highlight @ 10ten-ja-content.js:9901
highlightText @ 10ten-ja-content.js:11595
highlightTextForCurrentResult @ 10ten-ja-content.js:11829
applyQueryResult @ 10ten-ja-content.js:11782
lookupText @ 10ten-ja-content.js:11737
await in lookupText (async)
tryToUpdatePopup @ 10ten-ja-content.js:11690
onPointerMove @ 10ten-ja-content.js:10877
```

<img width="1488" alt="image" src="https://github.com/birchill/10ten-ja-reader/assets/5049892/fd093883-0c05-4291-b087-0a8dfff8cd2c">



I don't know if it happens everywhere, but it happens on e.g. NHK, Mainichi Shinbun, Asahi Shinbun, Wikipedia, ... Only thing not affected is text input though:

<img width="796" alt="image" src="https://github.com/birchill/10ten-ja-reader/assets/5049892/f9732737-b05e-43cc-91cb-9c1cec2a25ac">

**Comment by birtles** [comment]
Perfect! Thank you so much! That's a very helpful error message. I'll get on to fixing it once I can get to a computer. Thank you again!

**Comment by birtles** [comment]
I've submitted a fix to the Chrome extension store but it might be a couple of days before it is approved. Thanks for reporting this and sorry for the trouble!
