### ISSUE TITLE
Z-Index issues in iframes

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#13]
The popup does not appear on top at all times. For example, in Twitter Polls use iframes. 

If the text is at the bottom of the iframe, the Rikaichamp window cuts off at the frame border.

![Twitter Screenshot](https://user-images.githubusercontent.com/28300/32879381-05085bd4-caaa-11e7-8420-ed541bdfc68a.png)

**Comment by birtles** [comment]
Yeah, I've noticed that too. That might be a bit tricky to solve. Ideally we'd just run the content script in the top-most window and make it traverse iframe contents but I'm not sure if web extensions have the same security restrictions as regular content does with regard to traversing cross-domain iframes. I suppose we could `postMessage` from child to parent if necessary but that's still going to be complicated.

**Comment by Tomalak** [comment]
Yeah, I already figured that. I'm sure it can be solved eventually, but it's gonna be tricky to solve this in a general way. In the case of twitter polls it's not cross-domain at least.
