### ISSUE TITLE
Kanji headword not shown even if direct match

### ISSUE THREAD

**Issue by SaltfishAmi** [birchill/10ten-ja-reader#1361]
![image](https://github.com/birchill/10ten-ja-reader/assets/14184974/28e80bfd-6673-4568-9d72-f4f022b3743f)

![image](https://github.com/birchill/10ten-ja-reader/assets/14184974/8e12146b-04ab-4e54-baa4-fec834d9b7bb)

and "usually kana" does not make any sense when the headword does not contain any kanji.

see also: #438 #877 #979

**Comment by birtles** [comment]
In this case that headword is `sK` meaning "search-only kanji". These headwords are for looking up only but not intended to be shown. They usually correspond to very rare or incorrect forms. We deliberately don't show these forms, even if they match.

Do you think it would make more sense to show them when they match? Perhaps we should show them but faded out or some such?

Hiding the "usually kana" annotation when no kanji headwords are shown makes sense.

**Comment by SaltfishAmi** [comment]
I think at least the direct match should be shown, with some kind of marking indicating that it is not often used.

**Comment by birtles** [comment]
Sure, that makes sense. I'm currently in the middle of some pretty major refactoring (including some steps that will get us a bit closer to finally being able to change the UI language) but I've added this issue to my list of minor bugs to fix in the next release.

**Comment by birtles** [comment]
How about this:

![image](https://github.com/birchill/10ten-ja-reader/assets/1232595/4179f491-b601-487c-bead-17d8986dc3a1)

And for readings:

![image](https://github.com/birchill/10ten-ja-reader/assets/1232595/29d82053-92cd-4046-8510-91079204f875)
