### ISSUE TITLE
Review zh-Hans translation

### ISSUE THREAD

**Issue by SaltfishAmi** [birchill/10ten-ja-reader#1363]
The 10ten reader added so many new features recently and I noticed that the translations were updated too.

You did an impressive work on the Chinese translation! Most of the new entries look good to me, but I did notice a few inconsistencies  and I plan to do a thorough check on that when I have time (possibly next weekend).

**Comment by birtles** [comment]
Thank you! That would be great. I used ChatGPT for most of the translations. It seems to do better than Google translate because you can give it more context for the translation.

No hurry on the check, the next release is still quite a while away given the current rate of progress.

**Comment by birtles** [comment]
Closed by #1386.
