### ISSUE TITLE
Parsing for 宣さない

### ISSUE THREAD

**Issue by birtles** [birchill/10ten-ja-reader#1467]
As reported by email, this is a [negative form of 宣する](https://www.edrdg.org/cgi-bin/wwwjdic/wwwjdic?1W%C0%EB%A4%B9%A4%EB_vs-s)

**Comment by Enellis** [comment]
I am curious about whether this form is actually in use. When searching for 宣さない on Google, there are only 2 or 3 unique results. If this form is commonly used, I would expect to see a distinct entry, like for 察する→察す or 達する→達す.

**Comment by birtles** [comment]
I also could only find a few references using Google, mostly of the form ファウルを宣さない or ヴァイオレイションを宣さない and mostly in the context of basketball.

I looked up the mail where this issue was reported and found the original report:

> 10ten doesn't correctly match all inflected forms of vs-s verbs. These verbs can either conjugate like v5s verbs (i.e. verbs ending in -す) or like vs-i/vs verbs (i.e. regular する verbs). Currently, only vs-i inflections are matched. For example, there's no match for 宣さない, [which is a valid negative form of 宣する.](https://www.edrdg.org/cgi-bin/wwwjdic/wwwjdic?1W%C0%EB%A4%B9%A4%EB_vs-s)

Does that clarification help?

**Comment by Enellis** [comment]
Thank you for the clarification.

Maybe I'm wrong but I don't think this is something we need to implement in the inflection parsing because as the [linked source](https://www.edrdg.org/cgi-bin/wwwjdic/wwwjdic?1W%C0%EB%A4%B9%A4%EB_vs-s) states:
> (*) for this type of verb both the さない and しない forms of negative are used, depending on the verb.

I think in cases where the さない form applies, there is always separate dictionary entry as す-Godan verb, so that in these cases it will correctly match all forms. Just like in the examples I mentioned in my previous comment there is an entry for [察する](https://www.edrdg.org/cgi-bin/wwwjdic/wwwjdic?1W%BB%A1%A4%B9%A4%EB_vs-s) and 察す as well as [達する](https://www.edrdg.org/cgi-bin/wwwjdic/wwwjdic?1W%C3%A3%A4%B9%A4%EB_vs-s) and 達す with the exact same definition. 

Also, when you search for the す-version on that site, you will be forwarded to the する version:
<img width="475" alt="Bildschirmfoto 2024-06-11 um 08 43 02" src="https://github.com/birchill/10ten-ja-reader/assets/6263698/abf552f2-2937-4a85-9d18-7091d3de13fd">

**Comment by birtles** [comment]
> I think in cases where the さない form applies, there is always separate dictionary entry as す-Godan verb, so that in these cases it will correctly match all forms. Just like in the examples I mentioned in my previous comment there is an entry for [察する](https://www.edrdg.org/cgi-bin/wwwjdic/wwwjdic?1W%BB%A1%A4%B9%A4%EB_vs-s) and 察す as well as [達する](https://www.edrdg.org/cgi-bin/wwwjdic/wwwjdic?1W%C3%A3%A4%B9%A4%EB_vs-s) and 達す with the exact same definitions.

I guess for 宣する the problem is there is no 宣す-Godan verb entry so if you try to use 10ten to look up ファウルを宣さない it will fail. Perhaps the author of the email encountered such content.

Perhaps we should submit an entry to JMDict for 宣す since it looks like 日本国語大辞典 (小学館) has it: https://kotobank.jp/word/%E5%AE%A3%E3%81%99-3137997

[Weblio](https://www.weblio.jp/content/%E5%AE%A3%E3%81%99) also has it but it has a warning that its conjugation data is programmatically generated:
> 文語活用形辞書はプログラムで機械的に活用形や説明を生成しているため、不適切な項目が含まれていることもあります。ご了承くださいませ。

I couldn't find it in 大辞林 however, only 宣する.

**Comment by Enellis** [comment]
Which dictionary do we trust more?
Given that nearly all Google results reference the same document (in different versions), there is a chance, that it was simply a mistake. Weirdly, in the same document also the form 宣しない is used.

**Comment by birtles** [comment]
> Which dictionary do we trust more?

I trust 日本国語大辞典 more than JMdict but in any case we can submit it to JMdict and the editors there can decide if it's worthwhile since they have access to more dictionaries than I do.

> Given that nearly all Google results reference the same document (in different versions), there is a chance, that it was simply a mistake. Weirdly, in the same document also the form 宣しない is used.

Yes, definitely. But "宣す" appears to be quite common appearing in a lot of official documentation in phrases like "開会・閉会を宣す", "承認する旨を宣す" etc.

**Comment by birtles** [comment]
Submitted as https://www.edrdg.org/jmwsgi/entr.py?q=2861608&svc=jmdict&sid=

**Comment by Enellis** [comment]
Great. Thank you, for taking care of this!

**Comment by enellis** [comment]
> Notify the owners of those online dictionaries and tell them to fix their software. [vs-c] is the correct verb tag for -す verbs.

Well, it seems that with new submissions they don't allow the す-Godan v5s tag on this kind of verb anymore. In the end, it is indeed something we need to implement in the inflection logic.

**Comment by birtles** [comment]
Thank you so much for looking into all this. I'm afraid classical Japanese verb inflections is not something I'm familiar with. I looked into it once in order to generate suitable localizations for the part-of-speech tags but I mostly found different sources used different terminology.

From what I understand, your proposal makes sense. Would there be a risk of matching multiple entries however? e.g. matching both the entry for 愛する and 愛す when looking up 愛せない for example?

For 五段化 we could just go with "Godanka" or perhaps we could try a little harder and go with "as Godan verb". Better still, do we even need to show the reason to be user?

**Comment by enellis** [comment]
> Would there be a risk of matching multiple entries however? e.g. matching both the entry for 愛する and 愛す when looking up 愛せない for example?

Yes, as this is already the case with many forms: 愛した, 愛して, 愛します, 愛される, 愛させる.

> Better still, do we even need to show the reason to be user?

I can imagine people being very confused, I certainly would be, when seeing 愛さない is matched with 愛する, as さない is not an inflection of する. In my opinion, knowing that this is because the verb can also be inflected as a Godan verb would instantly clear things up.

**Comment by birtles** [comment]
> > Would there be a risk of matching multiple entries however? e.g. matching both the entry for 愛する and 愛す when looking up 愛せない for example?
> 
> Yes, as this is already the case with many forms: 愛した, 愛して, 愛します, 愛される, 愛させる.

Oh, so it is!

Just a thought, I noticed that the [Supplementary comments for single-kanji ～する verbs](https://www.edrdg.org/wwwjdic/wwwverbinf.html#suru_tag) has:

> It has also been observed that when there is a related 五段 verb (愛す in the case of 愛する) the ～さない form tends to be used.

If that's true and all these する verbs that display the 五段化 behavior also have a corresponding す verb in JMdict (whether or not it is marked as v5s or vs-c) can we make the 五段化 rule have a to-type of `vs-c`?

If not, then I think your proposal makes sense. Although would we make the to-type for said rules be `vs-s`?

Sorry if my questions don't make sense, I might not be understanding the different cases properly.

**Comment by enellis** [comment]
> [Supplementary comments for single-kanji ～する verbs](https://www.edrdg.org/wwwjdic/wwwverbinf.html#suru_tag)

Thanks for sharing the link. That was some really useful information.

So if I'm understanding correctly, summing the things I read about this topic up, there are 3 categories for suru-verbs in JMdict:
- **vs-i:** These show no irregularities and inflect like any other noun that takes する.
- **vs-s:** These verbs generally inflect like vs-i verbs but may exhibit the following irregularities:
  - Inheriting the 未然形「せ」of the classical verb す, they can inflect to
    - せさせる (causative)
    - せられる (passive)
  - 五段化: Treated as す-五段 verbs, they can additionally inflect to:
    - さない (negative), さず (-zu)
    - そう (-sou)
    - せる (potential)
    - せ (imperative)
  - Treated as 「⚪︎しる」 一段 verbs, they can inflect to:
    - しず (-zu)
    - しさせる (causative)
    - しられる (passive)
- **vs-c:** These are old su-verbs that inflect according to the classical verb す.

> If that's true and all these する verbs that display the 五段化 behavior also have a corresponding す verb in JMdict (whether or not it is marked as v5s or vs-c) can we make the 五段化 rule have a to-type of `vs-c`?

Initially, I thought this was the case, but it is not. For example, the in the [Wikipedia article](https://ja.wikipedia.org/wiki/%E3%82%B5%E8%A1%8C%E5%A4%89%E6%A0%BC%E6%B4%BB%E7%94%A8#%E7%99%BA%E3%81%99%E3%82%8B%EF%BC%88%E5%8F%A3%E8%AA%9E%EF%BC%89) given example 発する has no corresponding entry for 発す but shows all of the above mentioned irregularities.

What I'd propose is
- for verbs tagged `vs-i:`: Nothing to do here.
- for verbs tagged `vs-s`: Integrating a new `vs-s` to-type is a good idea. We should implement the irregular inflection rule set targeting the new type and matching it to verbs with this tag only. Maybe we should generalize the 五段化 reason, so it can be applied to all of the above mentioned irregularities, to something like `irregular`.
- for verbs (solely) tagged `vs-c`: In the current state, avoid matching these with any deinflected forms, as we simply don't support classical inflections.

**Comment by birtles** [comment]
Thank you so much for the thorough investigation here! That's really helpful.

> What I'd propose is
> 
> * for verbs tagged `vs-i:`: Nothing to do here.
> * for verbs tagged `vs-s`: Integrating a new `vs-s` to-type is a good idea. We should implement the irregular inflection rule set targeting the new type and matching it to verbs with this tag only. Maybe we should generalize the 五段化 reason, so it can be applied to all of the above mentioned irregularities, to something like `irregular`.
> * for verbs (solely) tagged `vs-c`: In the current state, avoid matching these with any deinflected forms, as we simply don't support classical inflections.

That sounds perfect. Thank you again!

**Comment by enellis** [comment]
Great, I will start working on it once the 敬語-PR is merged.
