### ISSUE TITLE
Twitch video images triggering the addon

### ISSUE THREAD

**Issue by Jon-dog** [birchill/10ten-ja-reader#1517]
Visited Twitch and found that if I hover over video thumbnails of Japanese streamers while the extension is enabled it will start giving translations. However I have the extension set to only show translations if I press ctrl.

I imagine this is tied to some hidden text functionality?

![image](https://github.com/birchill/10ten-ja-reader/assets/7146672/8bae35d1-96f5-4e3b-9554-73bfe9e1f51f)
![image](https://github.com/birchill/10ten-ja-reader/assets/7146672/b09397e4-340b-450d-af05-0c4d497613aa)

**Comment by birtles** [comment]
Hi @Jon-dog, I think you probably want to enable "Ctrl" to show translations when hovering images too here:

![image](https://github.com/birchill/10ten-ja-reader/assets/1232595/a36351f0-c7c4-472f-a67e-9cdd8be11d30)

I believe it's picking up the alt text for those images.

**Comment by Jon-dog** [comment]
Ah yes that solves it, I must have blanked on seeing that option
