### ISSUE TITLE
Dark reader integration

### ISSUE THREAD

**Issue by birtles** [birchill/10ten-ja-reader#1549]
From the Chrome Web Store user support section:

> The pop-up window is being affected by the "Dark Reader" extension and changing into a dark yellow color, could you add the "darkreader" class so it gets ignored?

**Comment by SaltfishAmi** [comment]
For reproduce, make sure the "Dark Reader" extension is not set into dynamic mode because the popup seems to function correctly under this mode; use filter or filter+ and you can observe the bug

![image](https://github.com/birchill/10ten-ja-reader/assets/14184974/d715ce81-82e7-4859-aef5-ccb820f5c5a9)

**Comment by birtles** [comment]
Wow, thank you so much @SaltfishAmi!

**Comment by birtles** [comment]
I looked into this and as @SaltfishAmi noted, unless you use "Filter" or "Filter+" it appears to work correctly. If you use either of those modes, however, the add-on doesn't appear to respect the `darkreader` class.

It seems like the `darkreader` class only applies to `<style>` elements which is only relevant for the "dynamic" and "static" modes.

See:
- https://github.com/darkreader/darkreader/issues/4056
- https://github.com/darkreader/darkreader/discussions/7318

Until darkreader adds a means for other Web pages to opt-out content in the filter mode, users can go to "Dev tools" and then add `#tenten-ja-window` to their "INVERT" list:

![image](https://github.com/birchill/10ten-ja-reader/assets/1232595/a6de81bb-f2eb-4c9c-94f7-6a663ec40668)

After pressing "Apply" it should work. Sort of.

![image](https://github.com/birchill/10ten-ja-reader/assets/1232595/f7d99f98-e348-4387-81f1-daeff00037fb)

**Comment by birtles** [comment]
Closing this for now since I don't think there's anything we can do at the moment. We _could_ try to locate the darkreader styles and manipulate them but we'd be fighting with darkreader since it can update them dynamically.
