### ISSUE TITLE
Unable to use copy function on HTTP websites

### ISSUE THREAD

**Issue by Wobblebase** [birchill/10ten-ja-reader#157]
On HTTP websites navigator.clipboard is undefined. Is there a fix for this?
A simple workaround I found was to use google translate to turn the website into HTTPS.

**Comment by birtles** [comment]
Oh, that's a really good point. I never thought about that API being `[SecureContext]` only.

I will have a look into other APIs to use (from memory trying to do the copying from the background page doesn't work).
