### ISSUE TITLE
Sort exact katakana matches to the top

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#1610]
For katakana words there might be an exact headword match available, but in the pop-up it can be out-ranked by homophones.

An example is ヤク, where the relevant match is buried so deep in the list that wouldn't even be visible without scrolling in a normal situation:

<img src="https://github.com/birchill/10ten-ja-reader/assets/28300/e048800a-3245-46aa-a2f1-ab5ec67af807" height="600" alt="screenshot of the 10ten popup for ヤク">

Would it make sense to prioritize results to the top of the list when they exactly match a (potentially katakana-only) search word?

**Comment by birtles** [comment]
Yeah, that makes sense. I wonder if the heuristic should be "entry has no kanji headwords or the match is on a 'nokanji' headword". For example, a lot of animals have a katakana headword that's marked as "nokanji" like [クジラ](https://www.edrdg.org/jmwsgi/entr.py?svc=jmdict&e=1099740).

**Comment by Tomalak** [comment]
クジラ is an interesting one, because I'd actually like to see 鯨 show up as a result as well, which it currently doesn't.

**Comment by Tomalak** [comment]
Edge cases like クジラ aside, a relatively cheap approach would be to check for string equality (after half-width normalization) and sort exact matches with headwords to the top. For katakana only, I think even considering alternative word forms wouldn't be necessary.
