### ISSUE TITLE
We shouldn't lookup words when tapping a text box

### ISSUE THREAD

**Issue by birtles** [birchill/10ten-ja-reader#1654]
On mobile, we allow taps to lookup words without having to use the puck. However, [we take care to avoid doing lookups on buttons and links](https://github.com/birchill/10ten-ja-reader/blob/4ccdbd81327a92806fe30794241dd03562d0913f/src/content/content.ts#L303-L309).

We should extend that to text boxes too. It's annoying when you tap a text box with Japanese text in order to focus it and we end up showing the popup for the text under the tap.

Presumably we'll need to ensure we cover `contenteditable` elements too.

**Comment by StarScape** [comment]
I might try my hand at this once #1653 is merged, if you don't care. I'm all for improving the experience on mobile.

**Comment by birtles** [comment]
By all means go for it! Thank you!
