### ISSUE TITLE
10ten extension prevents cutting in the address bar in Edge browser for macOS

### ISSUE THREAD

**Issue by thesla13** [birchill/10ten-ja-reader#1697]
Hello!

A while back I have started having trouble using copy, paste and cut operations in the address bar of Edge browser for macOS. 
I would hit Cmd+C, but nothing would be copied. Cmd+X — and nothing would be cut.
I thought the problem could be caused by some of the browser extensions I use, since I use a lot, some 35, of them, and such hiccups do occasionally surface. And indeed, when an "InPrivate" window would be used (where most of the extensions are turned off), the problem would disappear.

So I then had to go through the said ~35 extensions, one by one, turning them off, and looking if the behaviour changes. And that has proven much trickier and more time consuming to investigate than it sounds, because, it turned out, there were two culprits, each in his own way. Moreover, the culprits are related. (And I may be making it sound like bad detective fiction, but, boy, did I spend some time with it.)

So the trouble is caused by two mouse-hover-pop-up-dictionary extensions. 10ten and [LiuChan](https://github.com/Paperfeed/LiuChan). The latter is a Chinese dictionary built upon RikaiChan foundation.
Interestingly, it turned out, each messes things in its own way. 10ten prevents cutting in the address bar, while LiuChan — prevents copying from there.

The coherence seems to be complete: turning any of the extensions off makes the relevant problem go away; turning it back on makes it reappear. Whether or not the extension is active makes no difference: as long as it's not completely turned off in the extensions manager within browser settings, the relevant function would not work.

Another detail is that it doesn't just "not work". It "not works" in a very irregular way, and I wasn't able to deduct any pattern there. But, for instance, 10ten, when on, prevents cutting. I would select something in the address bar, press Cmd+X, nothing would happen. Then, sometimes, after a couple of seconds, the selection would still be cut and would appear in the clipboard. Yet at other times — nothing, I would click elsewhere, deselect the address bar, switch apps, copy or paste something else, then come back to Edge, click in the address bar, and __then__ the cut would happen without me pressing anything — a minute later! I cannot imagine what would have to be happening under the hood.

I am going to contact the developer of LiuChan as well. But could you please, please look into what could be going on here?

Thank you!
And thank you so very much for your most wonderful extension and your hard work!

**Comment by thesla13** [comment]
Uh-oh 🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️

I've had Ctrl+X and Ctrl+C keyboard shortcuts assigned to enable/disable 10ten and LiuChan. X and C. Cut and Paste. I've reassigned them and everything works perfectly now.

Why on earth would Ctrl+X/C, not Cmd+X/C, mess with copy/paste on macOS, not Windows, — is still beyond me though. But that has to be a next person's problem, I am almost dead of exasperation as it is.

Again, I'm very sorry about the false alarm.
And, again, — thank you so much for the most wonderful extension!

**Comment by birtles** [comment]
@thesla13 Thank you so much for taking the time to investigate and report this. That's great to hear you found the cause. That does seems like an Edge bug that Ctrl+X overrides Cmd+X like that. I understand you're probably exhausted from this investigation but if you ever feel up to it, you might like to try and reproduce it in Chrome for MacOS and if you can, file a bug on Chromium.

There is some complicated mapping between Cmd/Ctrl so that shortcut keys can be synced between browser instances on different platforms and it's possible something is getting mismatched. I made a few notes here once: https://github.com/birchill/10ten-ja-reader/blob/843be31c0a28894fa3f4d799ebdb59883497c1ae/src/options/ToggleKeyForm.tsx#L204-L230

**Comment by thesla13** [comment]
@birtles 

Thank you for the reply, Brian! 
I did install Chrome for macOS and did try setting Crtl+C/X as a shortcut for a number of extensions. In all of the cases Ctrl+C/X did overide pressing the Cmd+C/X, the extension function would be toggled, and nothing'd cut or copied. So, yes, it does not seem to depend on an extension, or be an Edge thing, but a Chromium issue up the stream.

You think I should file a bug? And where do I do that for Chromium? Their [GitHub page](https://github.com/chromium/chromium) doesn't seem to have an Issues section? Is [this site](https://issues.chromium.org/issues?q=status%3Aopen+ctrl+cmd) the right place?

Thank you so much!

**Comment by birtles** [comment]
Hi @thesla13!

> Is [this site](https://issues.chromium.org/issues?q=status%3Aopen+ctrl+cmd) the right place?

Yes, that's the one! Thank you!
