### ISSUE TITLE
Result ordering with 進んでいます

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#1722]
Currently (v1.18.0), the results for「進んでいます」will sort「進ぶ」to the top after deinflection, although「進む」is the more common word, as indicated by the star.

![image](https://github.com/birchill/10ten-ja-reader/assets/28300/34ec84a9-6a42-4993-89e0-f0644c8e4209)

Would it make sense to boost common words in the results, everything else being equal?

**Comment by birtles** [comment]
Yes, that's definitely a bug. We should be sorting that correctly. Perhaps we're sorting each individual lookup separately (i.e. the lookup for 進ぶ and the lookup for 進む separately) but we really should sort across all lookups of the same source length.

**Comment by Tomalak** [comment]
That was quick, thanks! 😃
