### ISSUE TITLE
Popup is being affected by the zoom level of the current page

### ISSUE THREAD

**Issue by rampaa** [birchill/10ten-ja-reader#1763]
When I zoom in/out a page the popup also gets zoomed in/out, which is not desirable. Would it be possible to make it so that popup is not affected by the zoom level of the current page?

OS: Windows 10
Browser: Firefox v125.0.3

**Comment by birtles** [comment]
Thanks for reporting this. I had a look into it and it seems like there's no way to detect the browser zoom level. For example [[1]](https://stackoverflow.com/questions/1713771/how-to-detect-page-zoom-level-in-all-modern-browsers) and [[2]](https://github.com/tombigel/detect-zoom) discuss various approaches but none of them work correctly in all case.

(A lot of articles mention `devicePixelRatio` but that will be non-1 on high resolution screens regardless of zoom. Other articles mention the visual viewport API that that only covers pinch zoom, not browser zoom.)

**Comment by rampaa** [comment]
Thanks for looking into it! It's a shame but it seems like it's not actionable, so I will close the issue. Thanks again!
