### ISSUE TITLE
Revisit bundled font

### ISSUE THREAD

**Issue by birtles** [birchill/10ten-ja-reader#1799]
Feedback from [AMO](https://addons.mozilla.org/en-US/firefox/addon/10ten-ja-reader/reviews/2082402/):

> the bundled font change is jarring, I'd much rather use a font that is consistent with my system. The "a" used to have a hat (not round) and the characters used to have smaller proportions, for example.

We can easily fix the "a" to have a hat again but I wonder if we should make the bundled font opt-out?

**Comment by SaltfishAmi** [comment]
Yes, tbh I don't like the idea of bundled font either. The new look makes me feel like although my computer is running Windows the extension popup is running Mac, which is a very weird feeling.

**Comment by birtles** [comment]
Thanks for the feedback! That's good to hear. I've posted a Twitter poll just to try to get a bit more feedback: https://x.com/10tenstudy/status/1797848455479779828

**Comment by stnrik** [comment]
Can you put in an option to turn it off or change it to something else?
It's really annoying to parse the new font.

**Comment by birtles** [comment]
> Can you put in an option to turn it off or change it to something else?
> It's really annoying to parse the new font.

Sure, we'll do something about this. I didn't realize how much people would dislike it. I'm still trying to gauge if it's better to add an option or just remove it altogether.

**Comment by Enellis** [comment]
I personally like the font, think it's visually quite pleasing and would continue to use it even when optional, but I also share @SaltfishAmi's concern that the popup doesn't feel native anymore. For me it feels very linuxy, running it on macOS.

**Comment by garret1317** [comment]
I would appreciate an option to switch back to the system/default font.
The new bundled font is fine enough, but I prefer the one I had before.

**Comment by birtles** [comment]
Comparing some different options on Windows 11:

![image](https://github.com/birchill/10ten-ja-reader/assets/1232595/48693b87-cc78-4c19-844b-fb106ca0eb75)

Unfortunately my system is using Japanese so there's no actually much English text to compare there.

**Comment by SaltfishAmi** [comment]
> Comparing some different options on Windows 11:
>
> [image]

I don't think the Arial one actually looks like Arial.

The Meiryo one (which is default on my system) matches well with Segoe UI and Microsoft YaHei (Chinese) on my machine. The other fonts are too fine while Meiryo has a good degree of roughness on my non-high-resolution monitor.

**Comment by birtles** [comment]
This time again with English locale and rendered from Chrome:

![image](https://github.com/birchill/10ten-ja-reader/assets/1232595/168f4714-335d-410a-b8a3-be7b5b08b104)

**Comment by SaltfishAmi** [comment]
On my computer (windows 11), the lowercase L in Arial is a straight line.

**Comment by birtles** [comment]
> > Comparing some different options on Windows 11:
> > [image]
> 
> I don't think the Arial one actually looks like Arial.

It should be. I tried hard coding to Arial (instead of `sans-serif`) and got back the same result so I'm pretty sure it's Arial.

> The Meiryo one (which is default on my system) matches well with Segoe UI (English) and Microsoft YaHei UI (Chinese) on my machine. The other fonts are too fine while Meiryo has a good degree of roughness on my non-high-resolution monitor.

We were previously specifying `Meiryo, sans-serif` so that Windows users would get Meiryo if there system had it but Mac users would end up with Helvetica.

I think what you're telling me is that we probably want an option to revert to the previous `Meiryo, sans-serif` behavior as opposed to an option to "use the system default" (i.e. just `sans-serif`).

**Comment by birtles** [comment]
> On my computer (windows 11), the lowercase L in Arial is a straight line.

Oh, that's because we're specifying various font features: `'calt', 'case', 'cv01', 'cv03', 'cv04', 'cv11', 'ss03'`. That's also why Arial has a single-story "a" in that screenshot. Without the font features it looks like:

![image](https://github.com/birchill/10ten-ja-reader/assets/1232595/e6c68fe3-8a4b-4663-9296-7d8281341cc0)

**Comment by SaltfishAmi** [comment]
Why is the font features specified? Any particular reason?

**Comment by birtles** [comment]
> Why is the font features specified? Any particular reason?

They are specific to the Inter font we were using specifying things like round quotes (see https://rsms.me/inter/#features) but it turns out `'ss03'` in particular applies to Arial and tweaks a number of things like the single-story "a" and the curled "l". We should drop those feature settings when we're not using Inter.

**Comment by birtles** [comment]
Judging by comments here and the Twitter poll, it seems like enough people like the new font that it's probably worth keeping in some form. My current thinking is to introduce an option to switch between:

- Bundled fonts, i.e. 1.19 behavior
- System fonts meaning "Meiryo, sans-serif", i.e. 1.18 behavior

I think I'll make the bundled fonts the default option.

I hope to implement this in the next few days and release a new version soon (including a fix for #1802 at the same time if we can work out what's going on there). There's a bit of complexity to it since I'd like to make sure the bundled fonts don't get defined in the content script when they're not used since browsers may pre-emptively load those resources.

**Comment by StarScape** [comment]
I don't have Twitter and so cannot vote in the poll, but FWIW I quite like the new font.

**Comment by birtles** [comment]
> I don't have Twitter and so cannot vote in the poll, but FWIW I quite like the new font.

Thanks @StarScape! I've added an option for now which will default to using the new font. Just waiting to fix #1802 before releasing the new version.
