### ISSUE TITLE
Duplicate results of causative and causative passive forms of Ichidan verbs

### ISSUE THREAD

**Issue by enellis** [birchill/10ten-ja-reader#1849]
### Screenshot
<img width="400" alt="Screenshot" src="https://github.com/birchill/10ten-ja-reader/assets/6263698/ee911fa9-263e-463e-84f4-618ebeeb06fd">

### Description
Since the introduction of recognition for the masu-stem + する humble form, the causative (e.g. 食べさせる) and causative passive (e.g. 食べされる) forms of Ichidan verbs give duplicate results. This issue arises because these forms can be interpreted in two ways:
1. As the normal causative or causative passive form.
2. As the masu-stem plus the causative or passive form of する.

Once support for honorific prefixes is implemented, the recognition can depend on the existence of a prefix, eliminating the ambiguity. However, the question remains whether there is something we can do now to address this issue.

**Comment by birtles** [comment]
Thanks for reporting that! That's interesting that the entry appears twice. I thought it should produce two parallel reason chains rather than appearing twice. Do we have a bug in our deinflection logic?

**Comment by enellis** [comment]
After investigating the issue, I found that we do indeed have a bug in the deinflection logic. For Ichidan verbs, we lack a check to determine if the word is already present in the result array. I will submit a pull request with a fix for this issue tomorrow.

However, it will still display `< humble < causative or causative`, which I think is not ideal and could be a little bit confusing.

**Comment by birtles** [comment]
> After investigating the issue, I found that we do indeed have a bug in the deinflection logic. For Ichidan verbs, we lack a check to determine if the word is already present in the result array. I will submit a pull request with a fix for this issue tomorrow.

Great, thank you so much!

> However, it will still display `< humble < causative or causative`, which I think is not ideal and could be a little bit confusing.

Yes, perhaps we can address that in a subsequent patch. I think it might be ok to detect this special case and simplify the reasons chain if we encounter it.

**Comment by enellis** [comment]
> For Ichidan verbs, we lack a check to determine if the word is already present in the result array.

Okay, so this is actually not as trivial to fix as I thought. Let's take the deinflection process of 食べさせない for example. The underlined arrow <ins>→</ins> indicates that the rule was applied programmatically with no corresponding rule in the rule data array:

　 食べさせない
```ts
['ない', '', Type.IAdj, Type.IrrealisStem, [Reason.Negative]]
```
→ 食べさせ (Irrealis stem) with `[[Reason.Negative]]` as reason chain.
<ins>→</ins> 食べさせる (Ichidan or Kuru verb) with `[[Reason.Negative]]` as reason chain. 

There are two rules applicable now:
```ts
['させる', 'る', Type.IchidanVerb, Type.IchidanVerb | Type.KuruVerb, [Reason.Causative]]
['させる', 'する', Type.IchidanVerb, Type.SuruVerb, [Reason.Causative]]
```

Case 1:
- → 食べる (Ichidan or Kuru verb) with `[[Reason.Causative, Reason.Negative]]` as reason chain.
- → **Match!**

Case 2:
- → 食べする (Suru verb) with `[[Reason.Causative, Reason.Negative]]` as reason chain.
```ts
['する', '', Type.SuruVerb, Type.MasuStem, [Reason.Humble]]
```
- → 食べ (Masu stem) with `[[Reason.Humble, Reason.Causative, Reason.Negative]]` as reason chain.
- <ins>→</ins> 食べる (Ichidan or Kuru verb)
- <ins>→</ins> **A result with the same type already exists!** (Case 1)
  - In the standard not-programmatically-forwarding case we would start a new reason chain with the current reason. This is a pure forwarding case though, so there is no reason to start a new reason chain with. Also we would miss the `Humble` reason added in the previous step. How do we want to proceed now?
    - Naively merge both reason chains.
      - <ins>→</ins> 食べる (Ichidan or Kuru verb) with `[[Reason.Humble, Reason.Causative, Reason.Negative],  [Reason.Causative, Reason.Negative]]` as merged reason chain.
      - Displays `< humble < causative < negative or causative < negative`.
    - Something different.
      - What do we even want to display in the end? I somehow cannot think of a way that would precisely describe the situation. `< humble < causative or causative < negative`?

As a small side note: This problem occurs only with Ichidan verbs + させる or される. I can think of no other scenario in the Ichidan-programmatically-forwarding case in which we would need to deal with starting a new reason chain. At least for now.

**Comment by birtles** [comment]
Thanks for the thorough analysis here! Sorry for the delay.

Just a quick question, what would we lose if we dropped the following rule:

```
['する', '', Type.SuruVerb, Type.MasuStem, [Reason.Humble]]
```

We plan to handle the `お + stem + する` form later and that should cover a lot of 謙遜語 cases.

For common `stem + する` forms often the stem appears as its own entry in the database already, e.g. 寝返りする (and it's not really a humble form anyway, it's just a different way of saying it).

**Comment by enellis** [comment]
I'm sorry it took so long to respond; I've been quite busy over the past few days.

Hmm, as usual, you're probably right and it's best to drop this rule. I wanted 10ten to recognize common forms like (お)送りします, but it seems this feature just isn't mature enough without proper support for honorific prefixes. This issue and the cases you mentioned where the nominalized verb form is used in a non-honorific way should be proof enough that implementing this rule in the current state was not a good idea and leads to more problems than it is solving.

**Comment by birtles** [comment]
> I'm sorry it took so long to respond; I've been quite busy over the past few days.
> 
> Hmm, as usual, you're probably right and it's best to drop this rule. I wanted 10ten to recognize common forms like (お)送りします, but it seems this feature just isn't mature enough without proper support for honorific prefixes. This issue and the cases you mentioned where the nominalized verb form is used in a non-honorific way should be proof enough that implementing this rule in the current state was not a good idea and is leading to more problems than it is solving.

Great, thank you! Ok, let's drop that rule. I don't suppose there are any other cases where we can end up with duplicate matches (as opposed to multiple chains) that we need to worry about?

**Comment by enellis** [comment]
So I went trough the rule data array and checked every entry where there is another entry with the same `from` inflection string. After dropping that rule there should be no more complications.

**Comment by birtles** [comment]
I had a go a dropping that rule, but it looks like we still incorrectly recognize "食べされる" as causative passive.

**Comment by enellis** [comment]
To be honest, I wasn't aware that contracting せられる to される is incorrect for Ichidan verbs, as I've seen it used that way (as I now know, mistakenly) in the past. Fortunately, there is an easy fix, and I will send a PR to treat される as an inapplicable form.

**Comment by birtles** [comment]
> To be honest, I wasn't aware that contracting せられる to される is incorrect for Ichidan verbs, as I've seen it used that way (as I now know, mistakenly) in the past. Fortunately, there is an easy fix, and I will send a PR to treat される as an inapplicable form.

Thank you so much!
