### ISSUE TITLE
Make WaniKani kanji levels link to the corresponding page in WaniKani

### ISSUE THREAD

**Issue by birtles** [birchill/10ten-ja-reader#1876]
As reported by email:

> it [...] would be nice to have those WaniKani level labels linked to actual entries on their web site, if possible.

It looks like the URL structure is just `https://www.wanikani.com/kanji/` + `the (URI-encoded) kanji` so for 買 it would be https://www.wanikani.com/kanji/%E8%B2%B7.

I think we'd just have the link open in a new tab. If we wanted to be really fancy, for Firefox users we could let them specify which container to use to open WaniKani links but we probably don't need to do that until someone asks for it. It's already possible to configure certain sites to open with specific container tabs with the [Firefox Multi-Account Containers extension](https://support.mozilla.org/kb/containers#w_manage-site-assignments).

**Comment by fgolos** [comment]
Thank you for considering this enhancement. Additionally, while you are at it, it would also be helpful to link WaniKani level label on Words tab to the corresponding Vocabulary page, which follows quite similar URL structure, but "kanji" is replaced with "vocabulary":  `https://www.wanikani.com/vocabulary/ + the (URI-encoded) vocabulary`. For example, for 文化 it would be https://www.wanikani.com/vocabulary/%E6%96%87%E5%8C%96.

![image](https://github.com/user-attachments/assets/a928d5f3-e87b-464a-a7f1-4eb9546f6d46)
