### ISSUE TITLE
Add option to disable popup when pointing at images

### ISSUE THREAD

**Issue by ForAnAngel731** [birchill/10ten-ja-reader#1889]
Is there a way to disable popups when pointing at images? I'd like the popup to come up only when point at actual text.
![image](https://github.com/user-attachments/assets/5dc00a16-8b9a-44a4-a010-de72c90d37cb)

**Comment by birtles** [comment]
Hi!

You can more-or-less disable the feature by requiring Alt and Ctrl be pressed in order to show the popup:

![image](https://github.com/user-attachments/assets/38bc97ed-ad5b-402f-8bff-67d577430749)

That way you'd be very unlikely to accidentally trigger it.

Does that work?

**Comment by birtles** [comment]
Closing this for now since I think there's a suitable workaround.
