### ISSUE TITLE
Japanese calendar conversion mistakenly recognizes 0年 as 元年

### ISSUE THREAD

**Issue by SaltfishAmi** [birchill/10ten-ja-reader#1912]
![image](https://github.com/user-attachments/assets/0bfae1a7-21cc-446a-86c2-5fb432537c97)

I think this can be very confusing since 元年 is 1年, and we want to avoid mistaking it as 0年.

**Comment by birtles** [comment]
Yes, that's a bug. Out of curiosity, did you find content that has 明治０年 in it?

**Comment by SaltfishAmi** [comment]
I think I once found something like 明治0 not necessarily with the 年 suffixed, but still triggered the date conversion
