### ISSUE TITLE
Parsing for 揺蕩うた and 揺蕩うて

### ISSUE THREAD

**Issue by Moritz72** [birchill/10ten-ja-reader#1962]
Similar to [#1470 ](https://github.com/birchill/10ten-ja-reader/issues/1470) this also seems to be an irregular form (see [here](https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1141245176)). As far as I can see this is not yet handled in [src/background/deinflect.ts](https://github.com/birchill/10ten-ja-reader/blob/main/src/background/deinflect.ts).

**Comment by birtles** [comment]
cc @enellis
