### ISSUE TITLE
Pop up shows even when I set ctrl to be required (only for images)

### ISSUE THREAD

**Issue by gevhaz** [birchill/10ten-ja-reader#2028]
Thanks for the plugin – it's been super useful for me. I think I found a bug. I have configured 10ten to require the control to be held down for the popup to show. This works for text. But still when I hover an image, I get the popup, which is obviously not supposed to happen.

**Comment by birtles** [comment]
Hi @gevhaz! Thank you!

If I understand the issue correctly, I think it might be a case of the settings panel being confusing. There are two rows for controlling the popup keys:

![image](https://github.com/user-attachments/assets/890c019a-1f72-4c2b-a471-8f50e2ad94c7)

If you don't select any keys in the second row (for images), then the popup will show for images even when you don't press anything.

Is it possible you haven't selected "Ctrl" for the images row?

**Comment by gevhaz** [comment]
That's a very obvious setting now that you point it out :grin: 

Thanks for your patient answer :) Resolving.
