### ISSUE TITLE
Broken config on Safari: changes don't apply immediately, only apply after quitting Safari

### ISSUE THREAD

**Issue by ph0ngp** [birchill/10ten-ja-reader#2045]
Currently, on Chrome builds, everything works as expected: when you change something in the options page, for example, text highlight color to blue, popup theme to lightblue, show/hide romaji, the changes are immediately reflected in the options page (the blue highlight radio is selected, the lightblue preview popup is highlighted, romaji shown/hidden in the popup preview). And if you currently have another tab running with 10ten turned on, the option changes are immediately reflected in that tab, without the need to even refreshing that page.

However, on Safari builds, including both iOS and macOS, when you change something in the options page, those things do not work as expected: the radio and the popup theme not displayed as selected even after clicked, romaji not shown/hidden in the popup preview. And if you have another tab running with 10ten turned on, the option changes are not reflected even after you refresh the page or toggling the extension on/off. The changes are only applied after quitting Safari and open Safari again. This is very unintuitive and confusing.

Why is this happening for Safari but not for Chrome?

**Comment by birtles** [comment]
Oh, that's interesting. I hadn't noticed that. I thought they applied instantly on Safari too. That sounds like a bug.

Unfortunately I don't have a Mac or iPhone at home so I'll have to check next time I go to the office.

**Comment by birtles** [comment]
I think this might be a regression in Safari 18. @ph0ngp Can you confirm what version of Safari you're using?

**Comment by birtles** [comment]
Ok, it looks like the issue is that Safari passes `undefined` as the `areaName` to [storage.onChanged](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/storage/onChanged). I suspect this is a recent regression since this definitely used to work.

**Comment by birtles** [comment]
Filed [Webkit bug 281644](https://bugs.webkit.org/show_bug.cgi?id=281644) for this. I'll have to make up a workaround in the meantime.

**Comment by birtles** [comment]
> Can confirm that I'm on Safari version 18.0.1 (20619.1.26.31.7), same as yours

@ph0ngp Thanks! I've released a new version of the extension, version 1.22.0, which should hopefully fix this.
