### ISSUE TITLE
reign names calculator off by one year

### ISSUE THREAD

**Issue by wdgml** [birchill/10ten-ja-reader#2080]
Hovering over 安政二年, for example, gives "1856," but it should be "1855." It seems to be adding one extra year to the results (presumably adding 2 to the first year of the reign period; but only 1 should be added, since counting begins at 1, not 0). The same problem occurs for many, but not all, other reign periods.

**Comment by birtles** [comment]
Hi! Thanks for reporting this. I had a quick look into it and I think the issue is more complicated than that. Our era data says 安政 started in 1855:

https://github.com/birchill/10ten-ja-reader/blob/f105dd990b76be7889a47b3cfedb13e57d57df1e/src/content/years.ts#L313

Which, strictly speaking it did:

> 嘉永から安政への改元が行なわれたのは[グレゴリオ暦](https://ja.wikipedia.org/wiki/%E3%82%B0%E3%83%AC%E3%82%B4%E3%83%AA%E3%82%AA%E6%9A%A6)[1855年](https://ja.wikipedia.org/wiki/1855%E5%B9%B4)[1月15日](https://ja.wikipedia.org/wiki/1%E6%9C%8815%E6%97%A5)であり、[和暦](https://ja.wikipedia.org/wiki/%E5%92%8C%E6%9A%A6)が新年を迎えないうちに[西暦](https://ja.wikipedia.org/wiki/%E8%A5%BF%E6%9A%A6)だけが新年を迎えている期間であった。安政元年は西暦1855年1月15日から同2月16日までの短い期間であるため、和暦と西暦を一対一で対応させようとする場合、嘉永7年＝安政元年＝西暦1854年、安政2年＝西暦1855年となって実際とはずれが生じる。

As I understand it, before about 1873 when the Japanese calendar 旧暦 was aligned with the Gregorian calendar, Western years and Japanese years didn't strictly line up. So 安政 started in January 1855 in the Gregorian calendar but 安政2年 is also (mostly) 1855. Then there's the phenomenon where a new era is retroactively applied back to the start of the year which I guess would mean it started in 1854 in some sense.

I think handling this properly would be quite a bit more work but would probably be worthwhile to do.

**Comment by SaltfishAmi** [comment]
旧暦 is a deep rabbit hole down to abyss.
I suggest we first clarify to what degree do we want to rectify this problem - do we want to give the correct Gregorian year for each and every 旧暦 day? Or just give 2 probable years to every 旧暦 year?

**Comment by birtles** [comment]
I'm thinking the minimum would be two probable years (e.g. 安政2年 = 1855~1856, maybe even with the dates).

If we actually had a full date 安政2年1月16日 then it would be nice if we could actually translate that to a specific year, but I don't think that's strictly necessary.

**Comment by enellis** [comment]
[Here](https://homepages.cwi.nl/~aeb/go/misc/jdate.html) is a very good and detailed explanation for an accurate date conversion.

**Comment by wdgml** [comment]
You are all very much correct that it is a complicated issue, as the lunar years and solar years do not align, and occasionally a new reign period starts in the gap between the solar new year and the lunar new year. For precise dates (with a month and day), the year can be determined using conversion charts or online conversion tools. Where only a year is given, though, the usual custom in the field (here I am speaking as a professional Japan historian) is to use the generally corresponding Western year. So Ansei 1 would still be 1854, even if this is a bit odd from a strictly logical perspective. In any event, Ansei 2 would definitely be in 1855 (leaving aside the fact that for certain dates at the end of Ansei 2, after the solar new year, it was technically 1856 in the West). I'm attaching a conversion chart I created for the Edo period, just to illustrate this more clearly and completely. Perhaps you could use a ≈ symbol for years if the incommensurability is a concern? As for converting more precise dates, that seems beyond the expectations of a pop-up dictionary, and people can easily refer to online conversion tools. Thank you for your hard work on such an invaluable tool!
![Edo_nenpyo](https://github.com/user-attachments/assets/065ee52d-6994-44c9-9227-44cd303508bd)

**Comment by SaltfishAmi** [comment]
I kinda agree with the idea that day-to-day conversion is unnecessary (remember that Gregorian calendar starts from the 1580s, which is another deeeeeeeeep rabbit hole). 
I was kinda thinking about something like "安政2 = 1855.2.x - 1856.1.x", because I do agree with the point that 安政1 = 1854 is a little (if not extremely) confusing.

From the viewpoint of modern China (which still uses traditional calendar along with Gregorian), we will use the term "celebrate the new year" exclusively for the lunar new year, the term "last year" to refer to either the last Gregorian year or the last lunar year. When we say "last year is 2023", we were actually referring to something like "2023.1.22-2024.2.9 is 2023". But all of that happens in the Chinese context - when any part of this conversation happens in English, it suddenly becomes very confusing.

**Comment by enellis** [comment]
> I kinda agree with the idea that day-to-day conversion is unnecessary (remember that Gregorian calendar starts from the 1580s, which is another deeeeeeeeep rabbit hole).

That will always be a problem, though, even when just displaying the time span of one year. Using [proleptic](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar) Gregorian dates for all dates would be the simplest solution for that.

I've started working on [this](https://github.com/enellis/10ten-ja-reader/tree/date-conversion) branch, and I've already implemented a way to display the time span as you suggested:
<img width="322" alt="Bildschirmfoto 2024-11-09 um 01 44 07" src="https://github.com/user-attachments/assets/2c47321e-b0d0-41c5-800d-deecabdaca15">
(For years after 1873, it falls back to the current way of displaying, e.g. 令和元年 = 2019年.)

With the dataset I gathered, converting every date to a Gregorian date will also be very straightforward.

**Comment by SaltfishAmi** [comment]
It looks really great! I have two suggestions tho:

1. How about making the day and month part smaller font size than the year part, or have dimmer color? I'm not sure about this, just an 思い付き.

2. When displaying full date, PLEASE DO allow custom format or use the format from system or browser locale. PLEASE NEVER hardcode dMy.

Thanks,

**Comment by enellis** [comment]
> 1. How about making the day and month part smaller font size than the year part, or have dimmer color? I'm not sure about this, just an 思い付き.

That's a great idea. I haven't really thought about the design yet, as I wanted to implement the logic first. The day-to-day conversion should be styled differently as well, I think.

> 2. When displaying full date, PLEASE DO allow custom format or use the format from system or browser locale. PLEASE NEVER hardcode dMy.

It's currently using the `toLocaleDateString()`method from `Date`, so it should be in the browser's locale, but we can still think about allowing more customization.

**Comment by Tomalak** [comment]
Since most modern software conflates the concepts of „UI language“ and „locale“, `toLocaleDateString()` gives me undesirable outputs in all browsers I use. Being able to override the default behavior could be useful.

**Comment by birtles** [comment]
> I've started working on [this](https://github.com/enellis/10ten-ja-reader/tree/date-conversion) branch, and I've already implemented a way to display the time span as you suggested:

Thanks looks great.

I agree that doing a suitable localized date is tricky (for some users it might even end up being identical to the original date!) but I wonder if we could just always use YYYY.MM.DD? I think that's unambiguous and since we want to emphasize the year, putting it first makes the information easier to scan—particularly if we end up making the month and date smaller as @SaltfishAmi suggested.

**Comment by enellis** [comment]
> I wonder if we could just always use YYYY.MM.DD?

How about using YYYY年MM月DD日?

**Comment by birtles** [comment]
> > I wonder if we could just always use YYYY.MM.DD?
> 
> How about using YYYY年MM月DD日?

Yes, I think that would work too. (I find it a little harder to scan but at least it's unambiguous. Presumably anyone looking up years would know enough kanji to decipher that much, and if not, they can hover over the individual kanji anyway.)

**Comment by enellis** [comment]
This is the current state:

<p>
    <img width="373" alt="Bildschirmfoto 2024-11-11 um 21 12 00" src="https://github.com/user-attachments/assets/195b2337-cf98-49c0-8eb9-55abef8befe3"><br>
    <em>Year only.</em>
</p>

<p>
     <img width="424" alt="Bildschirmfoto 2024-11-11 um 21 13 53" src="https://github.com/user-attachments/assets/57bd6203-a33f-4251-a92d-bc9d2eece402"><br>
    <em>With month.</em>
</p>

<p>
    <img width="343" alt="Bildschirmfoto 2024-11-11 um 21 14 16" src="https://github.com/user-attachments/assets/81cfb5fe-89fc-4a55-8a48-c0bb4d7bdb65"><br>
    <em>Full date.</em>
</p>

Can't really say that I'm fully satisfied. Any thoughts or ideas?

**Comment by birtles** [comment]
Looks great to me!

**Comment by birtles** [comment]
@enellis Hi! Sorry it's taken so long to release this. It tooks me quite a while to debug rspack and although I submitted it to the different app stores over two weeks ago, the reviewer for addons.mozilla.org got tripped up by [a corepack issue](https://github.com/nodejs/corepack/issues/612) and misattributed it to this add-on so it's been stuck waiting for re-review. Hopefully they'll get to it soon enough.

Also, if you don't mind, could you email me at info@birchill.co.jp? I have something I'd like to ask but I couldn't find any means of contacting you other than through GitHub.

**Comment by enellis** [comment]
> [@enellis](https://github.com/enellis) Hi! Sorry it's taken so long to release this. It tooks me quite a while to debug rspack and although I submitted it to the different app stores over two weeks ago, the reviewer for addons.mozilla.org got tripped up by [a corepack issue](https://github.com/nodejs/corepack/issues/612) and misattributed it to this add-on so it's been stuck waiting for re-review. Hopefully they'll get to it soon enough.

Absolutely no problem! I've been following the rspack issue, but unfortunately, I couldn't be of much help since I didn't have a Windows machine at hand. I'm happy to hear that the update will soon be released in the Mozilla extension store.

> Also, if you don't mind, could you email me at [info@birchill.co.jp](mailto:info@birchill.co.jp)? I have something I'd like to ask but I couldn't find any means of contacting you other than through GitHub.

Sure, I sent you an email.
