### ISSUE TITLE
[Bug] [Safari] Translations aren't being displayed 

### ISSUE THREAD

**Issue by puggerino** [birchill/10ten-ja-reader#2148]
Hi! I've been using 10ten reader for a while on Safari (MacOS Sequoia 15.1.1, M1 Pro model). It worked amazing at first, but in the past month or so it stopped showing me translations, with only the reading in hiragana and the yen conversion still working
<img width="893" alt="Screenshot 2024-12-11 at 23 59 30" src="https://github.com/user-attachments/assets/c4ec4aef-1f79-41eb-83c0-65365efbc159" />
<img width="770" alt="Screenshot 2024-12-12 at 00 12 43" src="https://github.com/user-attachments/assets/32b089d9-b32b-4121-9c28-f79ba7ee258e" />

I've tried to uninstall it and re-install it multiple times with no luck. I've tried to install it on Opera on the same Mac and on Safari on iOS and it works fine there. Any help?

**Comment by birtles** [comment]
Hi! Sorry I'm away from my computer for a few days so I can't send screenshots but it sounds like the "Show definitions" setting has been turned off. There is a shortcut key for it (which I thought was turned off by default but I guess not) so perhaps you mistakenly pressed 'd' while the pop-up was showing and turned off definitions there?

In any case, you should be able to re-enable it from the settings page. Please let me know if that works. Thanks!

**Comment by puggerino** [comment]
Oh my gosh, it worked, I feel so dumb for realising sooner on my own and
wasting your time ahahah
Thank you so much for the patient support, have a nice day!

**Comment by birtles** [comment]
No problem at all! You too!
