### ISSUE TITLE
Pop-up z-index too low on Google Translate

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#217]
After translating a full website on Google Translate (by pasting a URL into Google Translate), the result will have mouse over pop-ups that show the original text of any paragraph. 

Rikaichamp's popup appears beneath them, like here for the word 事情 in a [translated Yahoo News article](https://translate.google.com/translate?hl=&sl=ja&tl=en&u=https%3A%2F%2Fnews.yahoo.co.jp%2Fbyline%2Fohnishiren%2F20200317-00168160%2F&anno=2):

![pop-up placement screenshot](https://user-images.githubusercontent.com/28300/76835515-89a0f480-682f-11ea-870d-17ca720bd245.png)

**Comment by birtles** [comment]
I can't seem to get that Google translate page to work with Yahoo News in either Firefox or Chrome at the moment.

I tried running it on asahi.com and the z-index seemed ok there:

![image](https://user-images.githubusercontent.com/1232595/79722205-99c05e00-831e-11ea-8d8f-205c85c133ab.png)

I wonder if something changed with Google translate? Can you still reproduce the problem?

**Comment by Tomalak** [comment]
Currently I can't seem to get Google Translate to work on any website at all. It will just show me the original text, no matter what I select.

They are currently moving some things around at Google Translate, I keep getting popups for modifications to how the history works. Maybe they broke more stuff in the back-end.

**Comment by birtles** [comment]
It seems to work for me now:

![image](https://user-images.githubusercontent.com/1232595/131613067-e74a627d-5eb1-49b7-bbe8-7cab37640f46.png)

Closing this for now.
