### ISSUE TITLE
Hover area for glyphs is misaligned.

### ISSUE THREAD

**Issue by delbonis** [birchill/10ten-ja-reader#278]
Not sure how to describe this properly.  This happens at least on YouTube and here.

Like take ミク. When you hover over the right half of the ミ it only highlights and displays information on the ク part.  And when you hover over the right part of the ku you don't see anything.

On current Firefox on Ubuntu 19.10.

Also: A license file would be appreciated :)

**Comment by birtles** [comment]
I think this might be an artifact of the `caretPositionFromPoint` behavior in Firefox. That is, I believe that API will return the next character if the supplied point is greater than 50% towards the far side of a character. On the other hand, when selecting text, it looks like the threshold is more like 70% or so (although it depends on which direction you drag it seems).

We could probably detect this case and decrement the start position to make the behavior more intuitive.

**Comment by nicolasmaia** [comment]
@delbonis Regarding the license, it's MPL: https://addons.mozilla.org/en-US/firefox/addon/rikaichamp/

But I agree a LICENSE.md file would be handy to have.

**Comment by birtles** [comment]
> @delbonis Regarding the license, it's MPL: https://addons.mozilla.org/en-US/firefox/addon/rikaichamp/

That might just be AMO's default value.

This is forked from Rikaikun, which is forked from Rikaichan, which is forked from RikaiXUL. I think RikaiXUL was distributed under GPL so, even though I've rewritten just about every line several times over, I guess this should still be GPL. Any advice would be appreciated though.

**Comment by SaltfishAmi** [comment]
I found this a somewhat annoying problem because this misalignment can even cross lines if the lines are splitted simply by `<br>`, like this:

![img](https://user-images.githubusercontent.com/14184974/83962158-a9dfcd00-a8cd-11ea-8a97-60c123e575eb.png)

red cross is the mouse pointer position when taking the screenshot.

This problem is not present if the lines are splitted by `<p>`.
