### ISSUE TITLE
Does not work with firefox epub readers

### ISSUE THREAD

**Issue by Sparteh** [birchill/10ten-ja-reader#479]
Is there a way to make Rikaichamp work on such firefox extensions as EPUBReader? Basically, on readers which open as as new tabs in firefox. I have tested it with a few different epubs which have copyable text, yet non of them worked.

**Comment by birtles** [comment]
Looking at the screenshots for [EPUBReader](https://addons.mozilla.org/firefox/addon/epubreader/) it appears to display the content using a `moz-extension://` URL. However, Web Extensions cannot introduce content scripts into `moz-extension://` pages. 

See [Match patterns in extension manifests](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns):

> The special value <all_urls> matches all URLs under any of the supported schemes: that is "http", "https", "ws", "wss", "ftp", "data", and "file".

[An answer in StackOverflow](https://stackoverflow.com/questions/52131490/how-can-i-execute-a-userscript-on-a-moz-extension-page) suggests the same thing.

So I don't think there's anyway for Rikaichamp to work with EPUBReader at this stage. Sorry 😢

**Comment by birtles** [comment]
Closing this for now since I don't think there's anything we can do here. Sorry.
