### ISSUE TITLE
Convert 畳 (and other Japanese units of measurement)

### ISSUE THREAD

**Issue by nicolasmaia** [birchill/10ten-ja-reader#642]
A common measurement of size for apartments is 畳. I'm sometimes asked by my friends how big my place is in 畳. Or they'll say something is x 畳, and when I ask them to convert to squared meters, they have no idea how to do it.

One complicating factor is that 畳 has different sizes depending on the region: https://suumo.jp/yougo/a/ichijou/

Still, it could be interesting if Rikai was able to convert it to metric or imperial units, for each of the known 畳 sizes.

An overview of other units can be seen here: https://en.wikipedia.org/wiki/Japanese_units_of_measurement

**Comment by birtles** [comment]
That's a really neat idea. According to https://ja.wikipedia.org/wiki/%E7%95%B3#%E7%95%B3%E3%81%AE%E5%AF%B8%E6%B3%95%E3%81%AE%E5%AE%9F%E6%85%8B 帖 is defined to always mean 1.62 square metres whereas 畳 is _at least_ 1.62 square metres for the purpose of real estate advertisements (the Suumo article says the same too it seems).

So doing 帖 should be straight forward. For 畳 however, ideally we would handle 四畳半 etc. too.

**Comment by SaltfishAmi** [comment]
Non-metric measurement units are always a pain in the neck for me. I still remember last time I translated a work to Chinese and I needed to write a reference explaining 畳. Then I was confused about the region differences and at last I picked the estate advertisement version as a standard.

This is also true for imperial units tho... In China many measurement handbooks have both 'US gallon' and 'UK gallon' thing. But I guess UK uses metric units now?

**Comment by Tomalak** [comment]
> But I guess UK uses metric units now?

You wish. :) Officially yes, practically no.

**Comment by birtles** [comment]
I've landed an initial implementation of this in 7991227.

![image](https://user-images.githubusercontent.com/1232595/124233331-b58fd880-db4d-11eb-98c8-0bc794661dc7.png)

I've also made it convert from square metres back to 畳.

![image](https://user-images.githubusercontent.com/1232595/124233167-88dbc100-db4d-11eb-8e8b-5e479248751a.png)

There are a few caveats though:

* I haven't yet made it show the alternative conversions based on regional differences in tatami mat sizes. I'll give that a try in a moment.
* A number of real estate sites use annotations like "洋6.7 洋5.2 LDK13.4", or "1K(洋室6.0・K2.0)" and it doesn't recognize those yet. I can try and add that but I'm afraid it might turn up too many false positives.
* The initial issue here was to cover other Japanese units of measurement too. I've only handled 畳/帖 here. Probably most of the work in this issue can be re-used for other units so we _should_ be able to pretty easily add the others. There are quite a lot though so I'd probably prefer to add them on an as-needed basis. What are units you commonly encounter that would be handy to have converted? Please comment here or file a separate issue for them.

**Comment by birtles** [comment]
> * I haven't yet made it show the alternative conversions based on regional differences in tatami mat sizes. I'll give that a try in a moment.

I had a go at doing this but I wonder if it's a bit too busy?

![image](https://user-images.githubusercontent.com/1232595/124239015-38b42d00-db54-11eb-850e-353c0462aeed.png)

![image](https://user-images.githubusercontent.com/1232595/124239088-4f5a8400-db54-11eb-9db9-e6f3657d8403.png)

**Comment by nicolasmaia** [comment]
> > * I haven't yet made it show the alternative conversions based on regional differences in tatami mat sizes. I'll give that a try in a moment.
> 
> I had a go at doing this but I wonder if it's a bit too busy?
> 
> ![image](https://user-images.githubusercontent.com/1232595/124239015-38b42d00-db54-11eb-850e-353c0462aeed.png)
> 
> ![image](https://user-images.githubusercontent.com/1232595/124239088-4f5a8400-db54-11eb-9db9-e6f3657d8403.png)

I don't think it looks too busy at all, thanks to the decreased font size. I like it a lot!

**Comment by Tomalak** [comment]
I think it looks perfect.

**Comment by Tomalak** [comment]
...although on second thought, it seems a little excessive to convert to m² with three digits of decimal precision. 

Nobody knows what 0.001 m² even means, at least not in the context of room size. Rounding to 1 digit of precision is plenty.

**Comment by birtles** [comment]
> ...although on second thought, it seems a little excessive to convert to m² with three digits of decimal precision.
> 
> Nobody knows what 0.001 m² even means, at least not in the context of room size. Rounding to 1 digit of precision is plenty.

Good call. It currently uses 4 significant digits which is why sometimes you get a third fractional digit. I'm going to make it round to two digits of precision since it seems like the listings from SUUMO in those screenshots show two digits.

**Comment by nicolasmaia** [comment]
So far, I've unfortunately not been able to enjoy this new feature on websites like this:
https://www.biccamera.com/bc/item/9314464

Due to the fact that 10ten doesn't parse half-width numerals :(

**Comment by birtles** [comment]
> So far, I've unfortunately not been able to enjoy this new feature on websites like this:
> https://www.biccamera.com/bc/item/9314464
> 
> Due to the fact that 10ten doesn't parse half-width numerals :(

Oh, sorry, that's not due to parsing half-width numerals, it's simply that I haven't released an updated version of the add-on with this feature yet.

I'm trying to gather together a bunch of major UI changes to release at once along with the name change in order to minimize disruption. Hopefully the next release will be ready next week.

For what it's worth, half-width numerals should work fine:

![image](https://user-images.githubusercontent.com/1232595/125706908-f8169679-14d2-4dad-bea1-2b8a172eca1e.png)

So should all the following:

* 6畳
* 六畳
* ６畳
* 六〇畳
* 六十畳
* 四畳半
* 6 畳
* 1.5 帖
* 6m2
* 6m<sup>2</sup>
* 6㎡
* 22.5平方メートル
* 22.5平方ﾒｰﾄﾙ
* 22.5平方㍍
* 22.5平㍍
* 22.5平米
* 十二平方米

**Comment by birtles** [comment]
This feature is finally available in the latest release. Thanks for your patience!
