### ISSUE TITLE
Entries in multiples languages

### ISSUE THREAD

**Issue by dabisu** [birchill/10ten-ja-reader#677]
English is my default dictionary language. However, after the last update spanish and english entries are shown. Yes, my system language (Windows) is spanish, but I just want to see dictionary entries in english, not spanish entries "when available". Could you please revert to the old behaviour, or a least add an option to show only english entries? Thanks.

**Comment by birtles** [comment]
Hi David!
Sorry to hear about that. Just to check, have you selected English in the options?

![image](https://user-images.githubusercontent.com/1232595/125764573-3517e9bb-9960-4df1-85b5-830693e85267.png)

If that is selected it _should_ only display English definitions. If other definitions are displayed even when English is selected then that's a bug I need to fix.

**Comment by dabisu** [comment]
Thanks for the fast response. Yes, English it's selected in the options. Actually, I haven't changed the configuration at all. But...forget about this report. I've checked it again (same page, same word: Youtube and 梅雨), and now it shows only 2 english entries. A moment ago it showed 4 entries (2 english and 2 spanish). Maybe it's a Firefox issue, because I see right now that my options menu is mixing english and spanish options. Sorry about the noise, if it happens again and it's reproducible I'll reopen the issue.

**Comment by birtles** [comment]
Thank you so much! Yes, by all means reopen the issue if it crops up again.

(For what it's worth, the default behavior is to follow the language preferences set in the browser for content but it probably tries to be a little bit too clever in some cases so I imagine there may be some cases where it's buggy.)
