### ISSUE TITLE
Superfluous CSS margin above calculations section in popup

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#684]
There are a couple of pixels of top margin when the popup shows a calculation. I don't think that's intentional?

![image](https://user-images.githubusercontent.com/28300/126058165-b18c9a7b-a383-4f3b-82f3-e168acb231f4.png)

**Comment by birtles** [comment]
Thanks! While it is intentional, now that you mention it, it probably would look better without it!

**Comment by birtles** [comment]
I went to fix this but I think that (a) with the tabs added it looks less odd, and (b) the gap is useful when we have multiple sections like the following:

![image](https://user-images.githubusercontent.com/1232595/126097376-b7cff516-f721-477b-b843-817334394985.png)

I will make it drop the background shading, however, when there are no other entries, e.g.

![image](https://user-images.githubusercontent.com/1232595/126097427-14766e25-f41a-4bcd-859c-2083e7bb9dde.png)

**Comment by birtles** [comment]
With the tabs it looks like the following:

![image](https://user-images.githubusercontent.com/1232595/126097735-462e38a8-f7ab-46b0-b116-783fff981835.png)

**Comment by birtles** [comment]
I'm going to mark this as fixed for now. Please let me know if you disagree.

**Comment by Tomalak** [comment]
> with the tabs added it looks less odd

Huh,, I didn't know there even _were_ tabs. How do I even enable them? I don't see an option for that in my settings.

But yeah, without the tabs it looks weird.

> I will make it drop the background shading, however, when there are no other entries, e.g.

That's one option., but things would be inconsistent when there are two sections (I've never seen that happen in real life myself, but apparently it's possible).

Instead of margin-top, you could margin-bottom all the sections and the tabs, so that it all falls into place naturally when the tabs are not there?
