### ISSUE TITLE
10ten "off" icon is almost invisible on dark themes

### ISSUE THREAD

**Issue by tobia** [birchill/10ten-ja-reader#687]
See screenshot:

![Screenshot_2021-07-21_15-29-15](https://user-images.githubusercontent.com/48756/126497218-e3859913-44f0-4212-895b-c99fcaa5e387.png)

**Comment by birtles** [comment]
Thank you for filing this! Oh yeah, that's terribly hard to see. Let me see if I can add a white glow or something to ensure it is still readable.

**Comment by birtles** [comment]
This should be fixed in version 1.1.3 released a few hours' ago.
