### ISSUE TITLE
Make icon configurable

### ISSUE THREAD

**Issue by birtles** [birchill/10ten-ja-reader#689]
[Review feedback](https://addons.mozilla.org/en-US/firefox/addon/10ten-ja-reader/reviews/1735526/):

> i just don't like the 10 logo on the toolbar, i am so used to the old kanji one, i hope you'll replace it with something japan-ish

It would be nice if you could configure the icon.

Unfortunately, the way we currently show update progress in the toolbar means we have to generate a lot of different icons (one for each progress value in both the enabled and disabled states). Furthermore, some platforms don't support SVG icons so we have to generate various resolution PNG icons and make sure each of them is pixel perfect. So this is a _lot_ of work but it's probably worth it.

If anyone else would like this, please comment here so I know it's worth the trouble!

**Comment by Tomalak** [comment]
Yeah, I'm also missing the Kanji icon to be honest  But I'm old and set in my ways. ;)

So if there was a way to switch back, I would, but I can also get used to it.

**Comment by birtles** [comment]
Got [another comment to this effect](https://twitter.com/jedinjapan/status/1418245450147287041):

> Unfortunately the 01s and 10s of icon visual language lean very heavily towards programming and not towards kanji. At a glance, even knowing the name had changed, I confused 10ten for another extension 3 times after the icon change. The kanji icon was rather distinct visually.

**Comment by birtles** [comment]
I'd like to try making this change. I thought about using 字 as the icon but it's a little bit busy. I wonder if 天 would do. It's simple, symmetrical (unlike 理), clearly Japanese (hopefully making it stand out from other unrelated icons), and also tied to the add-on name.

**Comment by Tomalak** [comment]
天 seems like a good choice to me!
