### ISSUE TITLE
Feature: Convert numbers / currencies

### ISSUE THREAD

**Issue by birtles** [birchill/10ten-ja-reader#691]
[From twitter](https://twitter.com/maximillianaire/status/1418126666862252036):

> Do you think similar support for numbers or currency would be possible in a future update? It always takes me a few seconds to parse numbers like 150億円 etc

I think there are a few things here:

* Expanding numbers, e.g. 150億 to 15,000,000,000 or 15 billion
* Similarly for kanji numerals like we already do for years / area
* Converting currencies, e.g. 150億円 to 146 million USD

The last part is hard but would be very helpful. We could have the user choose the destination currency and then have it refresh the rate once a day or so assuming there is a free API for that, that could handle a 100,000 requests or so per day.

**Comment by Tomalak** [comment]
You could also add a shortcut key for popping up a new tab with a Google search for "15,000,000,000 JPY in USD"

Which would side-step the 3rd party API issue and allow for more target currencies than free APIs provide.

**Comment by nicolasmaia** [comment]
@Tomalak I'm not a big fan of that one. Also, it opens a different can of worms as some users use different search engines to avoid Google etc. An in-built solution would be ideal.

**Comment by birtles** [comment]
I think I've found a cheap way of getting the exchange rates to be updated so I think we can make this inbuilt.

**Comment by pellul** [comment]
+1 @nicolasmaia 
I really appreciate the work done for the numbers conversion, but I'd like to be able to switch the currency conversion option off since I don't know where the feature gets its data from. It also takes extra space on the pop-up, some people won't especially need a conversion.

**Comment by birtles** [comment]
> I really appreciate the work done for the numbers conversion, but I'd like to be able to switch the currency conversion option off since I don't know where the feature gets its data from.

Thanks. That data is loaded from a CloudFront server I run at reader.10ten.study. It is downloaded to that server once a day from https://fixer.io/.

> It also takes extra space on the pop-up, some people won't especially need a conversion.

Yeah, I've been thinking about adding and option to hide it and just doing the number expansion so that 150億円 is displayed as 15,000,000,000円 (without the conversion part) but are you saying you don't want even that?

**Comment by birtles** [comment]
I've just released v1.4.3 which includes:

* An option to disable currency conversion (choose "(none)" as the currency)
* Expansion of plain numbers (e.g. 150億)

If you turn off currency conversion, it will fall back to the plain number expansion in many cases.

The plain number conversion should be fairly unobtrusive because it's very small and it only shows up when:

* There is at least one kanji in the character (e.g. you will never see it for ２０ etc.), _and_
* It matches more than any dictionary entry (e.g. it won't show up for 二十 or 五 or 100億)

I think that covers everything in this issue so I'm going to close it.

At some point I'd like to make the converted value use "million", "billion", and "trillion" when that makes sense (e.g. make it show "$1.25 billion" instead of "$1,250,000,000") but that's a refinement that can come later.
