### ISSUE TITLE
dictionaries don't switch; c does not open copy; j/k do not move window

### ISSUE THREAD

**Issue by cookieo** [birchill/10ten-ja-reader#699]
The subject says it all!

![image](https://user-images.githubusercontent.com/63935546/126964104-33065714-61b8-49e0-bd86-106b6f0e0460.png)

![image](https://user-images.githubusercontent.com/63935546/126964194-ffd5c009-3381-479b-8da0-850dff79f52d.png)

**Comment by birtles** [comment]
Oh dear! I wonder if there is some problem with ESR 78 compatibility. Can you confirm the page is in focus? (If it is not in focus the keys won't work.)

**Comment by cookieo** [comment]
Okay, everything seems okay now.  After sending in the report, based on my experience at Yahoo News Japan, I noticed on another site (DeepL - in the box for pasting the original to be translated) that everything functioned properly.  Thinking that maybe Yahoo  was unusual in some way, I just revisited Yahoo now and everything works there too.

Sorry for the false alarm.

**Comment by birtles** [comment]
No problem! I'm glad everything works. Thanks for following up here.

I'll close this issue for now but if it happens again, I'd love to know in case there's something to be fixed.
