### ISSUE TITLE
CSS Layout Fighting in Options Page

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#708]
The options page currently does this (Tenten 1.2.0, Firefox 90.0.2 64-bit, Windows 10)

![tenten](https://user-images.githubusercontent.com/28300/127621961-f17c2aea-1b24-48d4-be99-92bd1909329f.gif)

**Comment by birtles** [comment]
Interesting. It works for me so I wonder what's different. I've tried with Firefox 92 and Firefox 91 on Windows 10 and I can't reproduce that. I'll see if I can try with Firefox 90.

**Comment by birtles** [comment]
Hmm, I can't reproduce it in Firefox 90 either. Does it do it endlessly? Or only while downloading updates? Does it stop if you change the settings in any way?

The only other factors I can think of are:
* Different system fonts (I'm on Japanese Windows)
* Different display density/resolution (I'm on a HiDPI monitor of some sort with 150% magnification but even if I turn it down to 100% I can't reproduce)

**Comment by Tomalak** [comment]
Yes it never stops. Might be resolution related?

I'm on 2560 x 1440 px with 175% scaling.

**Comment by Tomalak** [comment]
...yep, that seems to be scaling-related. Going to 200% scaling makes it stop.

**Comment by birtles** [comment]
Hmm, that's interesting. I tried that same resolution and magnification using Firefox 90 and I still can't reproduce it. Maybe fonts are related too.

Ultimately it's probably a Firefox bug since I don't _think_ that options page is doing anything fancy. So if static content is producing layout thrashing it suggests an instability in Firefox layout code. Nevertheless we still need to fix it -- but it's a bit hard to know how without being able to reproduce it 🤔

**Comment by birtles** [comment]
If anyone can consistently reproduce this, perhaps the most helpful thing would be:

1. Go to `about:debugging`
2. Choose "This Firefox"
3. Find "10ten Japanese Reader (Rikaichamp)"
4. Choose "Inspect"
5. In the little frames icon in the top right open the drop-down and choose `/options.html`
6. Move the tab to a new window (e.g. drag the tab title downwards)
7. Use the inspect tool (the icon with the box and cursor on the far left of the inspector toolbar) to select the options panel
8. Progressively select elements and delete them until the flickering stops

If you can determine which element is causing the flickering then that will help us know what we need to fix.

**Comment by Tomalak** [comment]
I notice that it constantly triggers "overflow" at the `panel-section-db-summary` div, and in consequence, "scroll" events at the `<html>` element:

![image](https://user-images.githubusercontent.com/28300/127735726-23f32b76-c9a6-465d-be5f-a677763ba3eb.png)

It stops when I either

 - delete the entire `panel-section-db-summary` div, or
 - disable the CSS properties highlighted below. If I turn any of them back on, the problem reappears.

![image](https://user-images.githubusercontent.com/28300/127735750-1050ed93-ef37-485c-90fc-3510b14b745e.png)

It also stops when I remove any of the `<fieldset>` elements that contain icon selection, popup style and tab position.

Of course this could be a red herring because triggering a reflow of the layout could make it go away naturally.

It *also* stops when I delete the `key-grid`, or change it from `grid-template-columns: minmax(12em, auto) 1fr;` to a fixed value like `grid-template-columns: minmax(12em, 5em) 1fr;` - it could also be a bug in Firefox's grid layout code.

**Comment by Tomalak** [comment]
The smallest-possible change I found to stabilize the layout is going from

```css
.panel-section-db-summary > :not(:first-child) {
    margin-top: 20px;
}```

to 

```css
.panel-section-db-summary > :not(:first-child) {
    margin-top: 14px;
}```

but then again, this very possibly only circumvents the rounding issue in some internal layout code in Firefox from occurring, without addressing the root issue.

Another thing that works is disabling `flex-wrap: wrap;` in `.panel-section-db-summary > .db-summary-status`.

It really looks like it is margin- and/or flexbox-related, and as if too many things of equal priority on the page are relative to each other.

**Comment by birtles** [comment]
Yeah, this is really odd. I wonder if it's because Firefox manually sets the page height of the options page:

https://searchfox.org/mozilla-central/rev/4b88e0b8cca115009e82fdd65e5bf5812ff99128/toolkit/mozapps/extensions/content/aboutaddons.js#2446

Changes to the DOM of the page trigger that to be updated:

https://searchfox.org/mozilla-central/rev/4b88e0b8cca115009e82fdd65e5bf5812ff99128/toolkit/components/extensions/ext-browser-content.js#310

I wonder if we're running into trouble because of some of the responsive elements in the page.

e.g. maybe we have something like the following situation:

1. Do layout and overflow height producing scrollbars
2. `Extension:BrowserResized` event is dispatched and the height of the container is updated so now scrollbars are no longer needed
3. As a result we reflow and end up with a different (shorter) height
4. That triggers a new `Extension:BrowserResized` and we update the height again taking us back to (1)

That might fit with the observation that making converting the `grid` properties to something less responsive works around the problem.

**Comment by birtles** [comment]
Alright, I _think_ I might know a fix. I think if we put `overflow: hidden` on the root `<html>` element we might avoid the scrollbars appearing and re-appearing and causing the instability. We'll need to only do that for Firefox, however, since the other browsers probably need the scrollbars.

**Comment by Tomalak** [comment]
Sounds like a pragmatic fix to me

> We'll need to only do that for Firefox, however, since the other browsers probably need the scrollbars.

Don't forget to test on mobile Firefox :)

**Comment by birtles** [comment]
> Don't forget to test on mobile Firefox :)

I don't suppose you can help?

I've never even tried running it on Firefox for Android.

**Comment by Tomalak** [comment]
Sure, I can try to help with that! 

Disclaimer: I'm using mobile Firefox as my main browser, and I currently don't have 10-ten installed, but I can give it a go and if you have any specifics I should test, let me know.

**Comment by Tomalak** [comment]
...and I've hit the first roadblock - apparently 10-ten is not marked as compatible with Firefox for Android at the moment. 

I suppose that's only a matter of adjusting the manifest?

**Comment by birtles** [comment]
> ...and I've hit the first roadblock - apparently 10-ten is not marked as compatible with Firefox for Android at the moment.
> 
> I suppose that's only a matter of adjusting the manifest?

Sorry for the delay here. Firefox for Android only allows recommended extensions at the moment.

Information here: [Extensions in Firefox for Android Update](https://blog.mozilla.org/addons/2021/01/20/extensions-in-firefox-for-android-update/)

I think the criteria for being a Recommended Extension includes being "relevant to a general, international audience" (https://support.mozilla.org/en-US/kb/recommended-extensions-program) for which I don't think any foreign language tool will ever qualify.

That said, it can be installed on Firefox Nightly, see: [Expanded extension support in Firefox for Android Nightly](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/). I know some people are doing that although I've personally never tried.

**Comment by Tomalak** [comment]
Then let's disregard my cautionary remark. I was under the impression that Firefox for Android supported running all extensions, but I've never put that to the test. Thanks for the heads-up.

**Comment by birtles** [comment]
No problem. Some day I'd like to tweak Firefox for Android support so that if/when Mozilla do allow more extensions to run there we'll be ready to go.
