### ISSUE TITLE
Recognize 3つ 2つ etc the same way it recognizes １つ

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#709]
I'm aware １つ is recognized because it has its own dictionary entry proper, but it would be nice to have at least the irregular つ counters (and maybe 日 too?) recognized as well, with any kind numerals (half--width, full-width, Kanji).

**Comment by birtles** [comment]
Sorry, I didn't quite follow the scope of the issue here. Is it to support half-width numerals followed by つ/日 where there are dictionary entries, i.e. recognize 2つ, 6つ? I think for kanji there are already dictionary entries for 三つ、八つ etc.

Or is it for handling even those without dictionary entries? e.g. 123つ? In which case what would you expect it to display?

(On an unrelated note, it would be neat if one day we could do this for all counters and also show the correct reading, e.g. showing 4分[よんぷん] = 4 minutes)

**Comment by Tomalak** [comment]
> Is it to support half-width numerals followed by つ/日 where there are dictionary entries
> Or is it for handling even those without dictionary entries?

Well... that's a good question. I didn't really mean an number reading generator. While this might be an option - arbitrary number readings could be generated pretty easily - but I not sure how much worth this has.

However,  if 一つ and １つ, resolve, then 1つ should, too. If １４日 and ２０日 resolve, 14日 and 20日 should, to.

I have cross-checked, and at least for つ there are entries from 1-9 and for 日 there are entries from 1-31, so simply resolving half-width numerals would be quite enough here. 

Other things like 月 are regular enough to not need a reading hint, but they also all have entries, so why not include them.

Beyond that, things get flaky. 枚 only has dictionary entries up to 3, 千 is even missing a couple between 1 and 9, 台 only has 1, but all these read quite regular, so they are less of a concern.

I think for starters it wold be good to just resolve half-width numerals and link to the existing entries. A full-blown "counter- and numeral reading generator" seems a bit out of scope.

**Comment by Tomalak** [comment]
Wow, from looking at the source changes, this was a lot more complex than I had imagined. Thank you!

**Comment by birtles** [comment]
> Wow, from looking at the source changes, this was a lot more complex than I had imagined. Thank you!

Thanks! Unfortunately it looks like I messed it up leading to issue #749 which I've just now patched.

**Comment by Tomalak** [comment]
Luckily an easy fix. :)

**Comment by nicolasmaia** [comment]
I noticed this unfortunately doesn't quite work for 小1（cf. 小１）

**Comment by birtles** [comment]
> I noticed this unfortunately doesn't quite work for 小1（cf. 小１）

Fixed in 7b73ccf1bb3b8441feacc3203eade49ac88aac72 (not yet released)
