### ISSUE TITLE
Issues on facebook images

### ISSUE THREAD

**Issue by rizzoivan** [birchill/10ten-ja-reader#718]
I think 10ten is creating problems with images on Facebook.
Since the upgrade from Rikai Champ to 10Ten Reader, Facebook sometimes doesn't show images and instead shows a text with written "could be an image/picture representing the following text "etc..." (I translated in English by myself, because my browser is set to Italian)

I'll attach a screenshot.

![image_2021-08-09_04-31-08](https://user-images.githubusercontent.com/88851297/129245141-d4cd3e9d-c43f-4ea4-8069-1f75bfaf99b0.png)

**Comment by birtles** [comment]
Hi! Thank you for reporting this!

That's very odd. I don't know how 10ten could cause that. Can you confirm that if you disable 10ten and reload the page the images work?

**Comment by rizzoivan** [comment]
I did that, i'll let you know soon!

**Comment by rizzoivan** [comment]
I have to confirm that the problem is **NOT** 10ten. I disabled it for two days and the problem with Facebook images continues.

**Comment by birtles** [comment]
Thank you for letting me know. That's great to know it's not 10ten. I hope you can find out what the problem is!
