### ISSUE TITLE
Website layout is changed when the extension in enabled

### ISSUE THREAD

**Issue by huupoke12** [birchill/10ten-ja-reader#723]
- **Description**
The extension can change the website layout, which can break the website.
The website in the below video is: https://wiki.archlinux.org/title/Category:Installation_process
Website layout is preserved after disabling the extension.
I'm using Firefox 91.0.
- **Video**

https://user-images.githubusercontent.com/16283764/129469384-ca51f218-a94f-4001-a611-232012e3015a.mp4

**Comment by birtles** [comment]
Hi! Thanks for reporting this including the video too!
Unfortunately I can't reproduce this. Also, it seems odd that 10ten would interact with a completely English page.
Can you confirm that disabling 10ten fixes the problem?
If so, can you show me the settings page for 10ten or let me know if there are any specific settings you have changed?

**Comment by birtles** [comment]
Actually, it looks like this might be #724 (and might be specific to user agent style sheets on Arch Linux?). Can you confirm what platform you are using?

**Comment by birtles** [comment]
Actually, never mind I think I have worked it out over in #724.
