### ISSUE TITLE
Bug [v1.2.1]: does not work (again) for FIRST CHARACTER OF inputs and textareas in Google Chrome

### ISSUE THREAD

**Issue by emerencia** [birchill/10ten-ja-reader#725]
Hi Brian,

All the information is in my other ticket https://github.com/birchill/10ten-ja-reader/issues/605

You fixed it after my ticket, but now in v1.2.1 it is broken again. I'm having exactly the same problem as described in the ticket above, again.

**Comment by birtles** [comment]
Sorry about that! I've fixed it now and added a regression test so it doesn't happen again. It should be fixed in the next release later this week. Thanks for reporting the problem!

**Comment by birtles** [comment]
Version 1.2.2 was released yesterday so this should be fixed now.
