### ISSUE TITLE
[Feature request or bug report?] 10ten reader not active when in Firefox Reader View

### ISSUE THREAD

**Issue by PNeigel** [birchill/10ten-ja-reader#731]
As the title suggests, 10ten is not active when Firefox is in its Reader View. Is it possible to have it also work in reader mode?

**Comment by birtles** [comment]
Hi! Thank you for taking the time to file this issue!

Unfortunately Firefox does not allow extensions to run in reader view yet. There is [Mozilla bug 1371786](https://bugzilla.mozilla.org/show_bug.cgi?id=1371786) to track that but there does not appear to be any progress. See also #32 and #236.

Until Mozilla makes it possible to run extensions in reader view I don't think there's anything we can do I'm afraid.

I hope you don't mind if I close this issue for now.
