### ISSUE TITLE
The build version of each extension must be kept in sync with that of the host app

### ISSUE THREAD

**Issue by shirakaba** [birchill/10ten-ja-reader#732]
A trivial one, before I forget to mention it – I noticed a warning when building the iOS app extension target "10ten Japanese Reader Extension (iOS)", and it was complaining that its build number didn't match that of the host app, "10ten Japanese Reader (iOS)".

In this screenshot, I've corrected it to 7 (under TARGETS > "10ten Japanese Reader Extension (iOS)" > Identity > Build), but before that, it was 1, as the warning said. By changing it to 7, it matches up with the build number for the host app target.

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/14055146/130331700-4e32c916-2e2f-4b89-95f3-2d260309ddfe.png">

**Comment by birtles** [comment]
Thanks! Yeah, I haven't found the right way to do this yet. Currently I've been manually updating these each time I publish a new version using the steps here: https://github.com/birchill/10ten-ja-reader/blob/main/CONTRIBUTING.md#releasing-on-safari

e.g. https://github.com/birchill/10ten-ja-reader/commit/c9a341c90474a90889b2de7af530b78e9ff1816a

I've only been updating the Xcode 12 files though since once we switch to Xcode 13 we'll need to match up the latest numbers from what we've pushed to the App Store anyway. I don't think we need to worry about Xcode 13 for now?

**Comment by shirakaba** [comment]
Ah, if you've only been updating the Xcode 12 files, that would explain it.

I mainly thought it would be worth lining them up in the Xcode 13 project as it's one less thing for me to adjust (and hold as an untracked change) when deploying to iPhone. That said, the build numbers being out of sync didn't seem to be causing deployment problems up until now, so maybe it's not a problem in practice. I filed this when I was trying to figure out why I couldn't get the extension to run in Safari on the newest beta.

Best keep tracking this as it'll result in an App Store rejection of the build (maybe at validation time rather than review time) if not eventually addressed.

**Comment by birtles** [comment]
> I mainly thought it would be worth lining them up in the Xcode 13 project as it's one less thing for me to adjust (and hold as an untracked change) when deploying to iPhone.

By all means! We should do that.

> Best keep tracking this as it'll result in an App Store rejection of the build (maybe at validation time rather than review time) if not eventually addressed.

Right, but we'll need to update the numbers before submitting to the App Store in any case because it automatically rejects overlapping build numbers (or build numbers that are less than the latest submitted version) anyway.

**Comment by birtles** [comment]
> That said, the build numbers being out of sync didn't seem to be causing deployment problems up until now, so maybe it's not a problem in practice. I filed this when I was trying to figure out why I couldn't get the extension to run in Safari on the newest beta.

Right, I haven't had any problems deploying to my iPhone or iPad because of this.

**Comment by shirakaba** [comment]
> Right, I haven't had any problems deploying to my iPhone or iPad because of this.

Seems this is the case for me, too.

> Right, but we'll need to update the numbers before submitting to the App Store in any case because it automatically rejects overlapping build numbers (or build numbers that are less than the latest submitted version) anyway.

Good point, I'll close this as it'll self-resolve once we prepare for publishing.
