### ISSUE TITLE
interfering with login at just eat

### ISSUE THREAD

**Issue by triadne** [birchill/10ten-ja-reader#745]
I don't really understand how this is happening, but this addon is causing issues with my login at just-eat.co.uk
I've checked all my other addons and it is definitely this addon causing the problem. I visit the site and I can remain logged in while reading the menu, but as soon as i go to checkout, i cannot remain logged in and i cannot log in. as soon as i disable tenten, i can checkout just fine.

**Comment by birtles** [comment]
@triadne Thank you very much for filing this report! That sounds very frustrating.

I have tried to connect to just-eat.co.uk but it appears to block me because I am in Japan.

Unfortunately I don't have any good ideas about what might be causing problems for just-eat.co.uk and have not heard of similar problems on any other sites.

I'm afraid I will need your help to understand the problem better. If you have time to provide some of the following information that would be most helpful.

* What do you mean when you say that you cannot remain logged in and cannot log in? What exactly happens?
* When you experience problems, can you open up the browser console (press <kbd>F12</kbd>) and navigate to the "Console" tab and see if there are any errors reported there? Especially ones from `10ten-ja-content.js`. If you could take a screenshot and attach it here, that would be most helpful.
* Which browser are you using?
* What version of 10ten is installed?
* Have you changed any of the settings?

Thank you!

**Comment by triadne** [comment]
Hi,
basically, I visit the website and am auto logged in. I add items to my
order. I click checkout and I end up on a screen telling me to login. i put
my credentials in and click login and it reloads the page and asks me to
login again.
I have attached a screenshot with errors.
[image: image.png]
[image: image.png]
I don't really understand if any of this is relevant or tell you what you
need to know.
I'm using firefox and i believe it is all auto updated. it should all be
latest version.
I haven't changed any settings, in fact I actually refreshed firefox today
and reinstalled everything.

I took another screenshot and expanded the sections surrounding the code
so i could track which errors occur when i click on the checkout button.
I also went back and clicked the tenten icon to turn it off and tried again.
[image: image.png]
when I clicked the checkout button after disabling it, I was logged in and
the site worked as expected.
Jessica.

**Comment by birtles** [comment]
Hi Jessica!

Thank you very much for taking the time to follow up here. Unfortunately the screenshots don't appear on GitHub. Perhaps it does not recognise screenshots sent via email. Would you mind pasting them into GitHub instead? Thank you!

**Comment by birtles** [comment]
Without seeing the site, my best guess is that this could be the same cause as #747. I will try to fix that and see if it helps.

**Comment by triadne** [comment]
Hi, 
I didn't realise I could reply in github. This is cool. 
ok, images in order :-
![image](https://user-images.githubusercontent.com/29523389/132241458-01acd9db-6115-401c-9579-0814b77cefed.png)
![image-1](https://user-images.githubusercontent.com/29523389/132241471-c14875e3-2872-499d-a943-de170b379ed5.png)
![image-2](https://user-images.githubusercontent.com/29523389/132241495-90ed034d-bcb4-4096-a6f2-9d93f29c4fde.png)

**Comment by birtles** [comment]
Thank you very much!

I'm afraid I'm still not sure from that what is going wrong. There appear to be a lot of errors from another add-on. Maybe that add-on is interfering with 10ten. Can I ask what other add-ons you have installed?

It's still possible this is related to #747 so I will continue to work on fixing that for the time being.

**Comment by triadne** [comment]
I don't feel comfortable sharing that information. It feels like a security risk to share all my addons.
I will check disabling all addons  except for tenten though....
okay, this is with no other addons. just tenten.
![image](https://user-images.githubusercontent.com/29523389/132345867-11bd32a0-aba1-4045-82b0-83e62d6e2a2a.png)

**Comment by triadne** [comment]
I also thought I'd enable all my6 addons and disable tenten in my addons control panel. completely disabled. here is what the console looks like. the login is absolutely fine here. I don't know what all these errors are and if I should be looking to address them. 
![image](https://user-images.githubusercontent.com/29523389/132347333-a20a0781-c63a-4a67-b5ac-4daf4f0f3dfc.png)

**Comment by triadne** [comment]
wait a minute, can anyone see all these codes. is this putting my browser at risk? canyou save the pictures and tell me when you've got them, I shouldn'tleavethem visible like that

**Comment by birtles** [comment]
Thanks Jessica! That's great. I don't think there is too much risk in posting those screenshots. It doesn't show which add-ons are enabled (every installation of an add-on has a unique ID in Firefox) but someone might be able to guess from the filenames/function names (although the filenames in those screenshots are so common I don't think they could).

That's good to know that the login works without 10ten. Unfortunately it's still not clear what the problem could be. There's a chance #747 will fix it so it might be best to wait until that is released and try again after that.

**Comment by birtles** [comment]
Also, I have saved the screenshots as you suggested so you may delete them now. Thank you again.

**Comment by triadne** [comment]
ok, well I don't visit just eat that often, so if you can give me a heads up, I can check it out.

**Comment by birtles** [comment]
Hi @triadne, I've just released version 1.3.5 which includes a fix for a related issue. It should be available for Firefox already once your add-ons update (you can go to the add-ons page and ask it to check for updates).

If you have a chance to try again with 1.3.5 some time that would be much appreciated!

**Comment by triadne** [comment]
Hi, no problem. I just went there, put random stuff in my cart and went to checkout and it appears I'm logged in fine.  This appears to have resolved the issue on Just Eat too. Great job!!
Of course, it may happen again so I'll reply here if it does happen again?  After all, sometimes things appear to be fine at first glance, right?

**Comment by birtles** [comment]
Thank you very much! That's great news!

By all means, please let me know if you see any problems in future.

I will close this issue now, but if you notice problems I will re-open it so feel free to comment here even if the issue is closed.
