### ISSUE TITLE
Hovering over an image causes 10ten to popup in Firefox

### ISSUE THREAD

**Issue by sorashi** [birchill/10ten-ja-reader#750]
**Steps to reproduce:**
1. Open Firefox with 10ten installed
2. Go to https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt5cab0491730833db/61302f51504fe365615e4b40/09082021-Patch-Notes-11-18-Highlights.jpg
3. Hover over the image located there.

**Expected:** 10ten does not pop up
**Actual:** 10ten pops up with the following information:

![image](https://user-images.githubusercontent.com/6270283/132656292-9170ad1d-74d6-42be-b3f3-1e98f3354fb3.png)

**Additional info:** Firefox 92.0, 10ten 1.3.1. Tested in Normal and Private Firefox Window. **Cannot** be reproduced in Chrome.

**Comment by sorashi** [comment]
Maybe this has something to do with `img` `alt` attribute?

**Comment by sorashi** [comment]
Now I noticed #749, sorry

**Comment by sorashi** [comment]
As expected, does not happen in 10ten 1.3.2 anymore

**Comment by birtles** [comment]
No problem, thanks for filing the issue all the same. There are still a few cases where that popup shows when it probably shouldn't so let me know if you see any other odd cases.
