### ISSUE TITLE
Login issues with college web portal

### ISSUE THREAD

**Issue by SoupHere** [birchill/10ten-ja-reader#760]
I've noticed recently that my specific login portal to a college I attend will not work with this plugin running, I originally thought it was a browser issue but I figured I'd check the site on a private window and the login worked fine. Disable 10ten reader; the site logs in just fine.
From what I could gather the site uses Ellucian's Luminis Portal 5 to work and if I had to guess it has to do with how the plugin might pre-load the page into itself that makes the security features of the login portal upset and throw an error about the page not redirecting properly (the browser initially says this could be a cookie issues which threw me off but deleting cookies didn't help in this case)
The issues with logging in happen whether or not the plugin is actually 'active' or 'disabled' (no hover over for JP text) only if I manually go over to about:addons and disable the reader does the login work properly.
issues occur on latest version of Firefox 92.0

**Comment by birtles** [comment]
Hi @SoupHere!

Thank you very much for reporting this issue!

I wonder if there are any error messages in the browser console (the console that shows up when you press <kbd>F12</kbd>)?

I am currently working on issue #747 which might be related. I hope to have a fix for that released soon. It would be good to know if this is the same cause, however.

Thank you again!

**Comment by SoupHere** [comment]
There were a couple errors specific to the page,
the two errors in order of appearance:
first error:
GET [loginportalsitename]/favicon.ico
[HTTP/1.1 405 Method Not Allowed 0ms] with a detailed package I can try and put on a document somewhere since it's a full report, but seemingly unrelated
second error:
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).
and there is an associated javascript file "jquery-legacy.js:4263:7" that goes with that which is ~144kB

**Comment by birtles** [comment]
Thanks!

Unfortunately those two errors seem to be unrelated in this case. I guess we'll have to see if #747 fixes this or not.

**Comment by SoupHere** [comment]
Ah, I see, the issue must be more complex than I thought. If only the addon could run in some sort of a stealth mode while it was disabled to workaround this, but I suppose manually disabling it while you need to use the specific affected sites also works in the mean time.
(I'll keep an eye out over at #747 to check things out)

**Comment by birtles** [comment]
I've just now released 1.3.5 for Firefox which includes a fix for #747 so if you have a chance to check again some time after updating that would be much appreciated!

**Comment by SoupHere** [comment]
Issue with logging in has been resolved on Firefox 97.0 and Waterfox G3.2.5, thanks for the hard work!

**Comment by birtles** [comment]
That's excellent news. Thank you!
