### ISSUE TITLE
Can't scroll in popup window

### ISSUE THREAD

**Issue by velw** [birchill/10ten-ja-reader#767]
The window pops up when you hover over a kanji. Sometimes it has a scrollbar, presumably as there isn't space to display all the information. But as soon as you move the mouse towards the pop up window, you move it off of the kanji - so the window disappears. How are you supposed to scroll the scrollbar?

**Comment by birtles** [comment]
Hi!

Can I check of you are using a touchscreen device?

The scrollbars should only show on a touchscreen device (where you can scroll by touching the screen) because we haven't added a way to scroll by mouse yet.

**Comment by velw** [comment]
I hadn't thought of it because I never use it, but the screen on my laptop is touch-sensitive, yes.

It would be a real nuisance to have to switch between using the mouse and using a touch screen just to use this plug-in, though, since I never use touch. It would be good to be able to turn that feature off - there must be others who are also using a PC/laptop with a touch-sensitive screen but not using the touch interface.

**Comment by birtles** [comment]
I think our best option here is just to hide the scrollbars for now. The scrollable behavior was primarily added for iOS devices where the scrollbars don't show anyway.

Once we added a way to scroll using the mouse we can re-add them.

**Comment by velw** [comment]
Closing due to age.

**Comment by birtles** [comment]
Yes, I think this is now fixed by the mouse interactivity added in v1.12.
