### ISSUE TITLE
Does not work on Bookwalker's web reader on Safari

### ISSUE THREAD

**Issue by mxng** [birchill/10ten-ja-reader#773]
Here's what it looks like on Firefox when it is working normally:

https://user-images.githubusercontent.com/11084577/134602278-55e9239e-e3ff-41bd-beb7-ae5e5adefdf7.mov

And here's what it looks like on Safari:

https://user-images.githubusercontent.com/11084577/134602307-cea41c1a-fc82-4846-823d-207d03a29f84.mov

This is from bookwalker.jp 's web reader for their light novels, where when you highlight words on the viewer and the popup comes out for you to write any notes or highlights. The words on the popup are usually detectable on Firefox so I wanted to try it on Safari but it doesn't work.

**Comment by birtles** [comment]
Hi!

Thanks for reporting this. I suspect this has to do with the fact that Safari runs in a separate mode (`activeTab` mode) where only the page where the add-on only has access to the page(s) on which you enable it. If that popup is from an iframe on a separate origin then it won't work.

I'd like to investigate but when I open books on bookwalker.jp I don't see the highlight feature. I guess I need to create an account?

**Comment by birtles** [comment]
I managed to reproduce this and I _think_ what is happening is as follows:

* The popup element has class `ui-dialog`
* `ui-dialog` has this rule applied: `#viewer, .ui-dialog * { -webkit-user-select: none; user-select: none }`
* If we call `document.elementFromPoint(x, y)` passing in the mouse position we get back the corresponding `<div class="message">文字</div>` element which contains the selected/highlighted text.
* On Firefox, if we call `document.caretPositionFromPoint(x, y)` we get the corresponding text node for `文字`
* On Safari, however, if we call `document.caretRangeFromPoint(x, y)` (Safari doesn't implement `caretPositionFromPoint`) we get back the `ui-dialog` element

The Safari implementation sort of makes sense. You can't select that text so it won't give you that caret position and it appears to walk up the tree to find the first element whose text you _can_ select.

I suppose we could try something where, if:

* We end up finding no text
* We used `caretRangeFromPoint`
* At least one of the descendants of the returned element has children with `user-select: none` (or `-webkit-user-select: none`)

Temporarily apply a rule to drop the `user-select: none` from all elements in the document and try the lookup again.

However, the third condition there is hard to check efficiently, and adding rules and forcing a restyle is not very performant.

I'll have to think about this some more.

**Comment by birtles** [comment]
Unfortunately Chrome doesn't have the same behaviour as Safari so I can't easily write an automated test for this since we don't run automated tests in Safari at the moment.

Manual test case: https://jsbin.com/takayijibe/edit?html,css,js,output

**Comment by birtles** [comment]
What's more, Safari doesn't necessarily return an _ancestor_ of the node it should. In the bookwalker.jp case it appears to return the next sibling (with class `ui-widget-overlay`).

So I think this needs a different approach where we:

* Detect failing to get a text node
* Retry using `elementFromPoint`
* If we get a _different_ element back, _and_ it has `innerText`, _and_ it has `(-webkit-)user-select: none`
* Then we retry after clearing the `user-select` property

In my testing that appears to work.
