### ISSUE TITLE
Do not show popups when hovering over images

### ISSUE THREAD

**Issue by Lebon14** [birchill/10ten-ja-reader#781]
So, whenever you hover over an image and the image has Japanese metadata, 10ten reader pops up the romaji (in my case) for the characters in the metada.

Here's an example. Head to this pixiv artwork page:
https://www.pixiv.net/en/artworks/85131012

This is what you should see, for example:
![10ten hover issue](https://user-images.githubusercontent.com/5299469/135363046-1b70e068-7ae9-4d3a-8820-114f58cd9af7.png)

This is extremely irritating. Can we have an option to disable this please?
Thanks.

**Comment by birtles** [comment]
Hi @Lebon14!

Yes, there is already an option to disable that:

![image](https://user-images.githubusercontent.com/1232595/135370521-8f1d747f-0141-4ad0-ab48-a31f62333980.png)

(Sorry, I am using the Japanese version of Firefox).

If you choose <kbd>Ctrl</kbd> as the key for showing the popup for images it will never show unless you hold down <kbd>Ctrl</kbd>.

**Comment by birtles** [comment]
Please feel free to close this issue if this option solves the issue.

**Comment by Lebon14** [comment]
Oh, thanks. I didn't notice the option. Cheers.
