### ISSUE TITLE
Pop-up box overlapping the mouse cursor and kanjis it shows on epub reader

### ISSUE THREAD

**Issue by Rezel666** [birchill/10ten-ja-reader#803]
Using version 1.4.7 on Firefox with custom web/desktop readers. The extension itself working just fine, but box overlapping the word and cursor in reader is very annoying. 

Both web and desktop readers are bib/i  https://bibi.epub.link/

The cursor and source word right above the box on screenshot below.

![изображение](https://user-images.githubusercontent.com/92707850/137673751-1494381f-9801-4203-a776-f64c6ee82e2b.png)

**Comment by birtles** [comment]
This should be fixed in 1.4.8 which shipped yesterday.

**Comment by RawToast** [comment]
@birtles Hey I came across Bibi after finding tutu reader slow it’s large epubs. I can get 10 to display the circle and it seems very responsive compared to in TTU, but I get no definitions. This is on the latest version & iOS.

This is reproducible on their demo book. 
https://imadokishimane.bex.jp/ebook/?book=imadoki_0302
