### ISSUE TITLE
Numbers still cause dictionary popup sometimes

### ISSUE THREAD

**Issue by Fyren** [birchill/10ten-ja-reader#811]
Related issue #749 and commit https://github.com/birchill/10ten-ja-reader/commit/f62fa3872fea2b84fcf8747807c099064b6837f9.

Mousing over the text "64" causes a dictionary popup, even in the current release (1.4.8) for me on Firefox.

The displayed popup is for the name entry for 64, so maybe `name-search.ts` should have a similar change as the earlier fix?

**Comment by Fyren** [comment]
Using 1.26.1 on Firefox has this happening again in at least some cases.  Mousing over the text "64" on a page shows a dictionary popup.

**Comment by birtles** [comment]
Oops, look like I regressed that somewhere. Thank you for reporting this.

**Comment by birtles** [comment]
Test content: 64あ

**Comment by birtles** [comment]
It's certainly not a recent regression. Goes back at least 2 years.

**Comment by birtles** [comment]
Looks like the original fix was wrong. Should be fixed in the next release.
