### ISSUE TITLE
"Highlight matched text" causes Firefox settings font dropdown to flicker and be unselectable

### ISSUE THREAD

**Issue by JanneM** [birchill/10ten-ja-reader#829]
On Firefox for Linux, versions 93 - 94 when the "Highlight matched text" is enabled, you can't select a new font in the Firefox settings. The dropdown flickers and disappears when you move the mouse so selecting a font becomes very difficult or impossible. Other drop-downs seem to work fine.

**Comment by JanneM** [comment]
Update: once I deselected the option once, then reenabled it, the issue seems to be gone.  I've had the extension installed for years; could deselecting, then selecting the option again update or change something that's been "stale" since a much earlier version?

**Comment by birtles** [comment]
Hi @JanneM!

Thank you for filing this issue. I'm sorry about the trouble you faced.

It is a little surprising that 10ten is interfering with the Firefox settings. Add-ons are not applied to `about:` pages like the Firefox settings page so, in theory, it should not able to interfere. If 10ten is interfering with the settings page then it sounds like a significant bug, not only in 10ten but in Firefox itself. If it happens again I would definitely like to know!

I hope you don't mind if I close this issue now. I am more than happy to re-open it if there are still problems.

Thank you again.
