### ISSUE TITLE
笑点 (NaN歳)

### ISSUE THREAD

**Issue by nicolasmaia** [birchill/10ten-ja-reader#863]
笑点 is an interesting case that reveals two bugs. One is the fact that 10ten doesn't seem to know what to do with extant entities, saying they're _NaN years old_, and the other is that only `[person]`-entities should have 歳 appended to the years (in the Japanese version of the add-on).

**Comment by SaltfishAmi** [comment]
In English version it says `NaN y.o.`.

**Comment by birtles** [comment]
Thanks for reporting this. This should be an easy fix. (I'll get onto it once I get out of hotel quarantine and back to reliable Internet!)

**Comment by nicolasmaia** [comment]
お大事に！

**Comment by nicolasmaia** [comment]
How are you thinking of handling the non-person entries? I think having the current calculation is still useful, it just needs different wording.

**Comment by birtles** [comment]
> How are you thinking of handling the non-person entries? I think having the current calculation is still useful, it just needs different wording.

Oh, I was just going to drop the calculation for non-person entries. Do you know of any examples where it would be useful for non-person entries?

**Comment by nicolasmaia** [comment]
Well, I guess you're right,it can maybe just be dropped.
