### ISSUE TITLE
"failed to load source map" when opening devtools

### ISSUE THREAD

**Issue by Brawl345** [birchill/10ten-ja-reader#890]
When I open the devtools on any page I get the following warning:

```
DevTools failed to load source map: Could not load content for chrome-extension://pnmaklegiibbioifkmfkgpfnmdehdfan/10ten-ja-content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

Using Chrome 97. It's only a warning but it's kind annoying. Seems like Chrome can't load the source map from an external file inside extensions. Maybe embed it directly inside the JS?

**Comment by birtles** [comment]
Sorry about that. I can see that's really annoying.

I had a look into inlining the source maps but it makes the content script, for example, jump from 504Kb to 1.54Mb. Given we're injecting that into every page, I imagine that might add a least a little overhead.

We could just drop the source maps for Chromium like [they did in the React DevTools extension](https://github.com/facebook/react/pull/20079/files) but it might be better to just produce them as-is but drop the `#sourceMappingURL` comment from the content script for Chromium browsers like we already do for Safari.

**Comment by Brawl345** [comment]
Thank you very much!
