### ISSUE TITLE
Issues recognising words on pdf.js 

### ISSUE THREAD

**Issue by BigPuffDaddy** [birchill/10ten-ja-reader#938]
Hey there, thanks for making an extension for iOS. You are all life savers.

When reading PDFs in Mozilla’s pdf.js 10ten is unable to recognise words. It can recognise individual kanji, though. This is the same on both my iPad and PC. Yomichan is able to recognise words fine, so I assume it is an issue with this app rather than pdf.js. 

Thanks all.

**Comment by birtles** [comment]
Hi @BigPuffDaddy, thanks for filing this!

I'm sorry to hear 10ten isn't working with pdf.js. Can you please tell me:

- What browser you are using on your PC?
- What file you are viewing?

I just tried here on Firefox using https://mozilla.github.io/pdf.js/web/viewer.html and it works for me, e.g.

![image](https://user-images.githubusercontent.com/1232595/156948931-812f6253-6b2b-4e4b-87aa-65abe7001ae4.png)

Thanks!

**Comment by BigPuffDaddy** [comment]
Hello Brian,

Thank you for getting back to me. On PC I was using Firefox, attempted on
chrome also if I remember correctly. Here is the file, may have something
to do with the PDF not having properly selectable text.

Thanks!

**Comment by birtles** [comment]
Hi @BigPuffDaddy,

Thank you so much for getting back to me about this.

Unfortunately I was not able to receive the PDF file. I'm sorry for the trouble but would you be able to send it to me at info@birchill.co.jp instead?

Thank you!

**Comment by birtles** [comment]
I've fixed this in the development version but you won't notice any difference until I release a new version, perhaps some time next week.

**Comment by BigPuffDaddy** [comment]
Thanks Brian, you’re a legend!
