### ISSUE TITLE
Popup does not display on some sites

### ISSUE THREAD

**Issue by WhonderWy** [birchill/10ten-ja-reader#947]
# Environment
- Firefox 99.0.1 [64bit] on Windows 10 21H2
- 10ten v1.8.4

# Issue
Popup refuses to display on some sites

# Example Images
## Example of popup not displaying despite hovering
![image](https://user-images.githubusercontent.com/26218326/164845033-d3b8b0f3-8c2c-4d55-a0f6-23c2d16ab8be.png)
## Example of popup not displaying using puck
![image](https://user-images.githubusercontent.com/26218326/164845861-a6f8b49c-1b1f-46e3-b114-5a68558d9e81.png)
## Example of popup displaying on different site
![image](https://user-images.githubusercontent.com/26218326/164846343-f12447c4-b113-429a-8e0d-76443095b543.png)

# Comments
Will provide more information later.

**Comment by birtles** [comment]
Hi! Thanks for the report. Can you please let me know which sites the popup fails to display on?

**Comment by WhonderWy** [comment]
Thanks for the rapid response @birtles ! I'm out and away from my keyboard so I cannot provide an exhaustive list right now, but the sites shown in the examples I provided are the following:
- http://syosetu.com/
- http://youtube.com/
The issue with the pop up not displaying extends beyond syosetu.com however and I've noticed the pop up not displaying on sites such as Twitter and so forth.

**Comment by birtles** [comment]
Thank you for that!

I'm afraid I haven't ever experienced the popup not showing--unless it's a recent regression, perhaps. I just loaded syosetu.com and I couldn't reproduce it on any of the content there. I wonder if another add-on is interfering perhaps? I don't suppose you noticed any errors in the console when it happens?

**Comment by birtles** [comment]
For what it's worth v1.8.4 did rework some of the code where we add the popup to the page so it's quite possible that regressed something but I don't have any good guesses right now.

**Comment by WhonderWy** [comment]
Sorry for the wait.

I personally believe another add on may be responsible for the issue, since the issue did rear its head after the v1.8.4 update. Rather than a regression, however, I am thinking that the rework may have resulted in an addon interfering with the pop-up.

I plan to look at the code myself when I wake up later.

**Comment by WhonderWy** [comment]
I noticed something weird. 

While trying to find out exactly what was happening, I noticed that the scrollbar was changing... So I took a screenshot of the page and...
![image](https://user-images.githubusercontent.com/26218326/164951012-0a657ee0-ab0c-4f96-b671-761014217176.png)

**Comment by birtles** [comment]
> While trying to find out exactly what was happening, I noticed that the scrollbar was changing... So I took a screenshot of the page and...

That's definitely not expected! I can't quite imagine what might cause that.

If you're able to take a screenshot of the contents of the `tenten-ja-window` element while the popup is showing that might be a start. (Unfortunately, that can sometimes be hard to do because once you move the mouse the popup disappears. I often Alt-Tab to another app, move the mouse to the inspector area, then Alt-Tab back.)

Alternatively, if you have a list of all the add-ons installed I could try installing them to see if I can reproduce the problem.

Just thinking aloud, my best guess is this is related to https://github.com/birchill/10ten-ja-reader/commit/a3df6cf8cde7efab8cc22109b0c73c3a94d23ba6 and perhaps setting `position: absolute !important` on the container element might prevent whatever is interfering with the positioning from having an effect.

**Comment by WhonderWy** [comment]
Screenshots of inspector
![image](https://user-images.githubusercontent.com/26218326/165027497-71ddcf4f-f74f-4ec7-8717-006b3c726e3a.png)
![image](https://user-images.githubusercontent.com/26218326/165027617-93d917a1-bcc8-4821-b4e7-b49b22b57e9c.png)
Screenshot of page
![Screenshot 2022-04-25 at 15-46-19 事業所の労働者不足に家賃高騰の追い打ち](https://user-images.githubusercontent.com/26218326/165027762-a19d6a80-5e36-4fbe-9d57-85cc9eac406a.png)
Screenshot of addon z-index just in case.
![image](https://user-images.githubusercontent.com/26218326/165027908-a3c9cf6f-4339-4fa8-b088-37c5ec77726f.png)


I have my inspector as a separate window, so I didn't have to use the trick you mentioned.

**Comment by birtles** [comment]
Thanks! That's great.

With your help I was able to reproduce the problem. It appears that some add-on is causing the 10ten container to have `position: absolute` without also setting `left: 0px / top: 0px`, specifically this selector: `body ~ div:not(#gdx-bubble-host)`.

Judging from the other selectors in that rule, it's something to do with online shopping? (`wikibuy`, `earny`, `piggyWrapper` etc.)

That seems to easy enough to fix. We just need to force `position: absolute !important; left: 0 !important; top: 0 !important; z-index: 2147483647` on the 10ten container element.

**Comment by WhonderWy** [comment]
No, thank *you* for guiding me along the way!

I tried disabling the addons individually and in groups, but I don't think I disabled all the online shopping-related addons at once.
Now to work out which addon specifically is causing me grief...
