### ISSUE TITLE
10ten causes page scrolling issues on SPA websites

### ISSUE THREAD

**Issue by moka491** [birchill/10ten-ja-reader#959]
Hello!
I've been encountering a bug with 10ten on single page applications like https://www.nativshark.com,
where, if you visited a fairly tall website (say 2000px) and then click an SPA routing link to another page that is less tall (say 1000px), the DIV element "tenten-ja-window" will still be positioned using --top: 2000px, which makes the new page much taller than it should be. This then forces me to scroll back up to the actual content or to refresh (so that tenten-ja-window will be correctly positioned).

Unfortunately, nativshark is the only website I've encountered this on so far, but I don't really use 10ten on other sites to prove or falsify my assumption that it's a general issue. I just think that, given that 10ten takes care of the div positioning, it should be unrelated to the site it's used on, and is probably caused by lack of repositioning when using SPA-based routing.

I hope I can assist in working this out, potentially building a quick sample app to test this in isolation.

**Comment by moka491** [comment]
Hi again!
I create a minimal Next.js project that demonstrates this issue. 
You can find it here: https://github.com/moka491/10ten-test-project

Clone it, `npm i`, `npm run dev`, go to http://localhost:3000 and enable 10ten.
Then, when you scroll down and click the link on the bottom of the page, you'll head to a new page which is way shorter,
and yet you can still scroll down the same length as you could on the previous page.

You can also see it in this video:
https://files.catbox.moe/81qrt2.mov

I was able to reproduce it in both Firefox and Brave, both MacOS and Windows 10, with and without Adblock enabled (just to rule it out)

**Comment by birtles** [comment]
Wow, thank you so much! 🤩
I really appreciate all the work you put into that.
Unfortunately this is a particularly busy week for me (setting up a new office for Birchill so we can welcome someone to work on 10ten more-or-less full-time) so it might be a few days before I get to debug this properly but I just wanted to say thank you!

**Comment by RawToast** [comment]
> setting up a new office for Birchill so we can welcome someone to work on 10ten more-or-less full-time

I hope this isn't hijacking the issue, but I was wondering if there was any way to contribute e.g. like ko-fi or Patreon, as this has been so useful to me. So it's great to hear that.

**Comment by birtles** [comment]
> I hope this isn't hijacking the issue, but I was wondering if there was any way to contribute e.g. like ko-fi or Patreon, as this has been so useful to me. So it's great to hear that.

That's incredibly generous of you to suggest that.  Thank you. Eventually we want to set up a way for people to express their support but we haven't got there yet. For now, follows on Twitter or word-of-mouth promotion are the things that help most! Thanks again!
