### ISSUE TITLE
Toshiki Kadomatsu 角松敏生 has the wrong birthdate in the popup dictionary

### ISSUE THREAD

**Issue by swedishfeces** [birchill/10ten-ja-reader#968]
[](url)
![Screenshot (1)](https://user-images.githubusercontent.com/78284905/174721369-2713438a-1256-42ba-9755-bfb8e820f8ef.png)

should be 1960, not 1950.

**Comment by birtles** [comment]
Should be fixed now

![image](https://user-images.githubusercontent.com/1232595/175754979-5c17353f-fec3-46aa-9417-138fa1a7c7bf.png)
