### ISSUE TITLE
Dictionary tabs missing

### ISSUE THREAD

**Issue by Hektor6766** [birchill/10ten-ja-reader#982]
I can't see any dictionary tabs on my pop-up, no matter which margin I opt for. I cannot access the kanji or names dictionaries using hotkeys. Is there currently an issue with this feature?

**Comment by Hektor6766** [comment]
Re-installed add-on; tabs are visible but disabled, dictionaries indicate updating. Dictionary downloads complete, everything working, please disregard issue.

**Comment by birtles** [comment]
Great, glad to hear it resolved itself. Sorry about the trouble!
