### ISSUE TITLE
A kanji missing a kanji section

### ISSUE THREAD

**Issue by Esoppant** [birchill/10ten-ja-reader#983]
Hi, I just noticed that 複 does not have a kanji section in its information card when you hover over it; that is, it's greyed out and can't be accessed with the kanji card hotkey (screenshot: https://i.imgur.com/vruwFpQ.png). I don't remember seeing this in any other kanji, so I assume it's a bug?

**Comment by birtles** [comment]
Oh good find! Thank you for reporting this. That definitely looks like a bug. I'll look into it tomorrow!

**Comment by birtles** [comment]
I've fixed this now, but it's going to take a while for the fix to show up (it requires users to be on an updated reader when the affected kanji records are updated).

I'll release a new version later today so most users should see the fix tomorrow-ish, but at some point I'll need to trigger a full download for all clients to ensure everyone gets the update. Fortunately there are only three kanji affected (複, 復, 輹).
