### ISSUE TITLE
Popup beak appears in the wrong location when selection range is just at the edge of a line wrap

### ISSUE THREAD

**Issue by shirakaba** [birchill/10ten-ja-reader#995]
The consequence being that there is no way to move the mouse into the popup here. This is macOS Safari 16.0, with Reader 1.12.5.

Case 1:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/14055146/191454684-62acd897-4bc4-42fb-992f-ede765c8c183.png">

Case 2:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/14055146/191455954-9dbf5f1a-c74b-4932-b78a-c8ae5bb4c81e.png">

I believe this is the very same problem we encountered on 10ten (granted, I think it may have been for Chrome, and perhaps for collapsed selections?), whereby the start of the Range is interpreted as being at the wrap point (the line above) rather than where the selection box visually is, so we can dig up how we handled that there.

**Comment by birtles** [comment]
Looks to be a Safari-specific bug.

**Comment by birtles** [comment]
I believe this was fixed in f8fd8c57cf1173e85f5644beac18c5c65c89b41f
