### ISSUE TITLE
Popup "animates" when CTRL is released

### ISSUE THREAD

**Issue by claudiofreitas** [birchill/10ten-ja-reader#998]
When I hold the CTRL key and mouse over a Japanese word, 10ten will popup with the following appearance:

![image](https://user-images.githubusercontent.com/212832/193254206-b6def238-571d-4699-aed8-e0447b18da53.png)

When I release the CTRL key, 10ten's appearance will change to the following:
![Screen Shot 2022-09-30 at 19 39 07](https://user-images.githubusercontent.com/212832/193254253-16f8e6e8-76b7-4e5e-adbc-5d4599d11553.png)

I feel it would be better to maybe change the appearance only when CTRL is pressed again to make the popup pinned. Not sure if keeping the baloon or keeping the dashed line.

I usually keep holding CTRL either to navigate between many words while I read them and releasing when I finished using the extension but would like to keep reading, or when I am trying to position my cursor in the word I want and then release CTRL to also keep on reading. But the change of appearance usually takes my focus from the text to understand what happened in the popup.

I will try to include a GIF to visualize it better below.

![CleanShot 2022-09-30 at 20 02 25](https://user-images.githubusercontent.com/212832/193256709-efbd53bf-de9d-4cc0-9156-665ece0af64c.gif)

--
**Reproduced on:**
10ten v1.12.5
Firefox Nightly v107.0a1 (2022-09-29) (64-bit)
Mac OS v12.4

**Comment by birtles** [comment]
Interesting problem! I think I understand what you mean. One idea: could you turn off the mouse interactivity setting?

Then the arrow won't appear until you hit <kbd>Ctrl</kbd> a second time (after which point you can interact with the popup using the mouse).

**Comment by claudiofreitas** [comment]
Oh I didn't notice this option was available.
I think I've only played with the tab position option.
Thank you Brian, that solves it (for my use-case at least)!

Should I close this issue, or leave it open if this is still something worth checking?

**Comment by birtles** [comment]
Great! Glad to hear it!

I don't have any particularly good ideas other than the mouse interactivity setting at this point so let's close this for now.
